import type { AccessUser, PendingInvitation } from "./types";

const iso = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();
const future = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString();

export const adminCompanyUsersMocks: AccessUser[] = [
  {
    id: "u-100",
    fullName: "Mariana López",
    email: "mariana.lopez@rappi.com",
    company: "Rappi Colombia",
    role: "empresa_admin",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(0),
    invitedBy: "Camila Soto",
  },
  {
    id: "u-101",
    fullName: "Andrés Castro",
    email: "andres.castro@rappi.com",
    company: "Rappi Colombia",
    role: "empresa_user",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(2),
    invitedBy: "Mariana López",
  },
  {
    id: "u-102",
    fullName: "Paula Ruiz",
    email: "paula.ruiz@rappi.com",
    company: "Rappi Colombia",
    role: "empresa_user",
    status: "pending_mfa",
    mfaEnabled: false,
    lastSignInAt: iso(8),
    invitedBy: "Mariana López",
  },
  {
    id: "u-103",
    fullName: "Carolina Pérez",
    email: "carolina.perez@bancoandino.co",
    company: "Banco Andino",
    role: "empresa_admin",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(1),
    invitedBy: "Camila Soto",
  },
  {
    id: "u-104",
    fullName: "Felipe Arango",
    email: "felipe.arango@postobon.com",
    company: "Postobón S.A.",
    role: "empresa_admin",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(5),
    invitedBy: "Camila Soto",
  },
  {
    id: "u-105",
    fullName: "Ricardo Mejía",
    email: "ricardo.mejia@bavaria.co",
    company: "Bavaria S.A.",
    role: "empresa_admin",
    status: "suspended",
    mfaEnabled: true,
    lastSignInAt: iso(120),
    invitedBy: "Camila Soto",
  },
];

export const adminSuperAdminsMocks: AccessUser[] = [
  {
    id: "sa-1",
    fullName: "Camila Soto",
    email: "camila.soto@licenciame.com",
    company: "Equipo Licénciame",
    role: "super_admin",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(0),
    invitedBy: "Sistema",
  },
  {
    id: "sa-2",
    fullName: "Diego Marín",
    email: "diego.marin@licenciame.com",
    company: "Equipo Licénciame",
    role: "super_admin",
    status: "active",
    mfaEnabled: true,
    lastSignInAt: iso(3),
    invitedBy: "Camila Soto",
  },
  {
    id: "sa-3",
    fullName: "Laura Quintana",
    email: "laura.quintana@licenciame.com",
    company: "Equipo Licénciame",
    role: "super_admin",
    status: "pending_mfa",
    mfaEnabled: false,
    lastSignInAt: iso(14),
    invitedBy: "Camila Soto",
  },
];

export const adminInvitationsMocks: PendingInvitation[] = [
  {
    id: "inv-001",
    email: "tatiana.gomez@grupoexito.com",
    fullName: "Tatiana Gómez",
    company: "Grupo Éxito",
    role: "empresa_admin",
    invitedAt: iso(1),
    invitedBy: "Camila Soto",
    forceMfa: true,
    status: "pending",
    expiresAt: future(2),
  },
  {
    id: "inv-002",
    email: "marcela.velez@grupoexito.com",
    fullName: "Marcela Vélez",
    company: "Grupo Éxito",
    role: "empresa_user",
    invitedAt: iso(2),
    invitedBy: "Tatiana Gómez",
    forceMfa: true,
    status: "pending",
    expiresAt: future(1),
  },
  {
    id: "inv-003",
    email: "sergio.henao@tiendasara.com",
    fullName: "Sergio Henao",
    company: "Tiendas Ara",
    role: "empresa_admin",
    invitedAt: iso(8),
    invitedBy: "Camila Soto",
    forceMfa: true,
    status: "expired",
    expiresAt: iso(1),
  },
];
