export const accessStrings = {
  page: {
    title: "Accesos y usuarios",
    subtitle:
      "Gestiona usuarios empresa, super admins, invitaciones pendientes y permisos dentro de la plataforma.",
    inviteCta: "Invitar usuario",
  },
  tabs: {
    companyUsers: "Usuarios empresa",
    superAdmins: "Super Admins",
    invitations: "Invitaciones",
  },
  stats: {
    total: "Usuarios totales",
    active: "Activos",
    pending: "Invitaciones pendientes",
    superAdmins: "Super Admins",
  },
  status: {
    active: "Activo",
    suspended: "Suspendido",
    pending_mfa: "MFA pendiente",
  },
  invitationStatus: {
    pending: "Pendiente",
    expired: "Expirada",
    accepted: "Aceptada",
  },
  roles: {
    empresa_admin: "Empresa Admin",
    empresa_user: "Empresa User",
    super_admin: "Super Admin",
  },
  table: {
    headers: {
      user: "Usuario",
      company: "Empresa",
      role: "Rol",
      mfa: "MFA",
      status: "Estado",
      lastSignIn: "Último ingreso",
      actions: "Acciones",
    },
    invitations: {
      headers: {
        recipient: "Destinatario",
        company: "Empresa",
        role: "Rol",
        invitedAt: "Enviada",
        expiresAt: "Vence",
        status: "Estado",
        actions: "Acciones",
      },
      empty: "No hay invitaciones pendientes.",
    },
    empty: "No hay usuarios en esta vista.",
  },
  rowActions: {
    changeRole: "Cambiar rol",
    suspend: "Suspender usuario",
    reactivate: "Reactivar usuario",
    resetMfa: "Reset MFA",
    resend: "Reenviar invitación",
    revoke: "Revocar invitación",
  },
  toasts: {
    suspend: "Usuario suspendido (demo).",
    reactivate: "Usuario reactivado (demo).",
    roleChanged: "Rol actualizado (demo).",
    mfaReset: "MFA reseteada. El usuario deberá configurarla en el próximo login (demo).",
    invitationResent: "Invitación reenviada (demo).",
    invitationRevoked: "Invitación revocada (demo).",
  },
  changeRole: {
    title: "Cambiar rol",
    description: "El nuevo rol se aplica al iniciar sesión.",
    warning:
      "Cambiar a Super Admin otorga acceso total a la plataforma, incluyendo facturación y auditoría.",
    cancel: "Cancelar",
    submit: "Aplicar cambio",
    submitting: "Aplicando…",
  },
  resetMfa: {
    title: "Reset MFA",
    description:
      "El usuario deberá registrar un nuevo factor MFA en el próximo inicio de sesión.",
    warning: "Esta acción queda registrada en la auditoría.",
    cancel: "Cancelar",
    submit: "Resetear MFA",
    submitting: "Reseteando…",
  },
  invite: {
    title: "Invitar usuario",
    description: "Envía una invitación corporativa para acceder a la plataforma.",
    steps: { form: "Datos", preview: "Confirmación" },
    fields: {
      email: "Correo corporativo",
      emailPlaceholder: "nombre@empresa.com",
      fullName: "Nombre completo",
      fullNamePlaceholder: "Ej. Mariana López",
      company: "Empresa",
      role: "Rol",
      language: "Idioma de invitación",
      forceMfa: "Forzar MFA en el primer login",
    },
    roles: {
      empresa_admin: "Empresa Admin",
      empresa_user: "Empresa User",
      super_admin: "Super Admin",
    },
    languages: { es: "Español", en: "English" },
    errors: {
      emailRequired: "El correo es obligatorio.",
      emailInvalid: "Ingresa un correo válido.",
      emailPersonal: "Solo se permiten correos corporativos.",
      emailBlocked: "Dominio bloqueado por política de seguridad.",
      nameRequired: "El nombre es obligatorio.",
      companyRequired: "Selecciona una empresa.",
    },
    next: "Siguiente",
    back: "Volver",
    cancel: "Cancelar",
    send: "Enviar invitación",
    sending: "Enviando…",
    sentToast: "Invitación enviada (demo).",
    preview: {
      heading: "Vista previa del correo",
      subject: (productName: string) => `Te invitaron a ${productName}`,
      body: (name: string, role: string, company: string) =>
        `Hola ${name},\n\nTe invitamos a unirte a Licénciame como ${role} en ${company}. Haz clic en el siguiente enlace para crear tu contraseña y activar tu cuenta. La invitación expira en 72 horas.`,
      linkLabel: "Enlace de activación",
      mockToken: (token: string) => `https://app.licenciame.com/invite/${token}`,
    },
  },
} as const;
