import type { DSNavGroup } from "../DesignSystem.types";

const TODAY = "2026-04-23";

export const NAV_GROUPS: DSNavGroup[] = [
  {
    id: "get-started",
    labelKey: "designSystem:groups.getStarted",
    sections: [
      { id: "intro", labelKey: "designSystem:sections.intro.label", status: "stable", lastUpdate: TODAY },
      { id: "principles", labelKey: "designSystem:sections.principles.label", status: "stable", lastUpdate: TODAY },
      { id: "changelog", labelKey: "designSystem:sections.changelog.label", status: "stable", lastUpdate: TODAY },
      { id: "contributing", labelKey: "designSystem:sections.contributing.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "brand",
    labelKey: "designSystem:groups.brand",
    sections: [
      { id: "brand", labelKey: "designSystem:sections.brand.label", status: "stable", lastUpdate: TODAY },
      { id: "voice-tone", labelKey: "designSystem:sections.voiceTone.label", status: "beta", lastUpdate: TODAY },
    ],
  },
  {
    id: "foundations",
    labelKey: "designSystem:groups.foundations",
    sections: [
      { id: "colors", labelKey: "designSystem:sections.colors.label", status: "stable", lastUpdate: TODAY },
      { id: "typography", labelKey: "designSystem:sections.typography.label", status: "stable", lastUpdate: TODAY },
      { id: "radius", labelKey: "designSystem:sections.radius.label", status: "stable", lastUpdate: TODAY },
      { id: "spacing", labelKey: "designSystem:sections.spacing.label", status: "stable", lastUpdate: TODAY },
      { id: "borders", labelKey: "designSystem:sections.borders.label", status: "stable", lastUpdate: TODAY },
      { id: "animations", labelKey: "designSystem:sections.animations.label", status: "stable", lastUpdate: TODAY },
      { id: "shadows", labelKey: "designSystem:sections.shadows.label", status: "stable", lastUpdate: TODAY },
      { id: "icons", labelKey: "designSystem:sections.icons.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "components",
    labelKey: "designSystem:groups.components",
    sections: [
      { id: "buttons", labelKey: "designSystem:sections.buttons.label", status: "stable", lastUpdate: TODAY },
      { id: "cards", labelKey: "designSystem:sections.cards.label", status: "stable", lastUpdate: TODAY },
      { id: "kpi-card", labelKey: "designSystem:sections.kpiCard.label", status: "stable", lastUpdate: TODAY },
      { id: "empty-state-card", labelKey: "designSystem:sections.emptyStateCard.label", status: "stable", lastUpdate: TODAY },
      { id: "image-overlay-card", labelKey: "designSystem:sections.imageOverlayCard.label", status: "stable", lastUpdate: TODAY },
      { id: "top-item-row", labelKey: "designSystem:sections.topItemRow.label", status: "stable", lastUpdate: TODAY },
      { id: "avatar", labelKey: "designSystem:sections.avatar.label", status: "stable", lastUpdate: TODAY },
      { id: "forms", labelKey: "designSystem:sections.forms.label", status: "stable", lastUpdate: TODAY },
      { id: "badges", labelKey: "designSystem:sections.badges.label", status: "stable", lastUpdate: TODAY },
      { id: "materials", labelKey: "designSystem:sections.materials.label", status: "stable", lastUpdate: TODAY },
      { id: "frosted-header", labelKey: "designSystem:sections.frostedHeader.label", status: "stable", lastUpdate: TODAY },
      { id: "player", labelKey: "designSystem:sections.player.label", status: "stable", lastUpdate: TODAY },
      { id: "sidebar", labelKey: "designSystem:sections.sidebar.label", status: "stable", lastUpdate: TODAY },
      { id: "popover", labelKey: "designSystem:sections.popover.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "layouts",
    labelKey: "designSystem:groups.layouts",
    sections: [
      { id: "page-shell", labelKey: "designSystem:sections.pageShell.label", status: "stable", lastUpdate: TODAY },
      { id: "body-card", labelKey: "designSystem:sections.bodyCard.label", status: "stable", lastUpdate: TODAY },
      { id: "app-layout", labelKey: "designSystem:sections.appLayout.label", status: "stable", lastUpdate: TODAY },
      {
        id: "layout-dashboard-v2",
        labelKey: "designSystem:sections.layoutDashboardV2.label",
        status: "stable",
        lastUpdate: TODAY,
      },
    ],
  },
  {
    id: "responsive",
    labelKey: "designSystem:groups.responsive",
    sections: [
      { id: "responsive-overview", labelKey: "designSystem:sections.responsiveOverview.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-breakpoints", labelKey: "designSystem:sections.responsiveBreakpoints.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-layouts", labelKey: "designSystem:sections.responsiveLayouts.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-typography", labelKey: "designSystem:sections.responsiveTypography.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-spacing", labelKey: "designSystem:sections.responsiveSpacing.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-touch", labelKey: "designSystem:sections.responsiveTouch.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-navigation", labelKey: "designSystem:sections.responsiveNavigation.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-forms", labelKey: "designSystem:sections.responsiveForms.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-tables", labelKey: "designSystem:sections.responsiveTables.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-modals", labelKey: "designSystem:sections.responsiveModals.label", status: "stable", lastUpdate: TODAY },
      { id: "responsive-checklist", labelKey: "designSystem:sections.responsiveChecklist.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "dashboard-v2",
    labelKey: "designSystem:groups.dashboardV2",
    sections: [
      { id: "dashboard-v2-layout", labelKey: "designSystem:sections.dashboardV2Layout.label", status: "stable", lastUpdate: TODAY },
      { id: "dashboard-header", labelKey: "designSystem:sections.dashboardHeader.label", status: "stable", lastUpdate: TODAY },
      { id: "kpi-row", labelKey: "designSystem:sections.kpiRow.label", status: "stable", lastUpdate: TODAY },
      { id: "credit-usage-chart", labelKey: "designSystem:sections.creditUsageChart.label", status: "stable", lastUpdate: TODAY },
      { id: "top-tracks", labelKey: "designSystem:sections.topTracks.label", status: "stable", lastUpdate: TODAY },
      { id: "platform-breakdown", labelKey: "designSystem:sections.platformBreakdown.label", status: "stable", lastUpdate: TODAY },
      { id: "recent-activity", labelKey: "designSystem:sections.recentActivity.label", status: "stable", lastUpdate: TODAY },
      { id: "wallet-section", labelKey: "designSystem:sections.walletSection.label", status: "stable", lastUpdate: TODAY },
      { id: "alerts-section", labelKey: "designSystem:sections.alertsSection.label", status: "stable", lastUpdate: TODAY },
      { id: "dashboard-empty-v2", labelKey: "designSystem:sections.dashboardEmptyV2.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "catalog",
    labelKey: "designSystem:groups.catalog",
    sections: [
      { id: "catalog-page", labelKey: "designSystem:sections.catalogPage.label", status: "stable", lastUpdate: TODAY },
      { id: "catalog-header", labelKey: "designSystem:sections.catalogHeader.label", status: "stable", lastUpdate: TODAY },
      { id: "filter-panel", labelKey: "designSystem:sections.filterPanel.label", status: "stable", lastUpdate: TODAY },
      { id: "track-card", labelKey: "designSystem:sections.trackCard.label", status: "stable", lastUpdate: TODAY },
      { id: "track-row", labelKey: "designSystem:sections.trackRow.label", status: "stable", lastUpdate: TODAY },
      { id: "track-list", labelKey: "designSystem:sections.trackList.label", status: "stable", lastUpdate: TODAY },
      { id: "themed-cards", labelKey: "designSystem:sections.themedCards.label", status: "stable", lastUpdate: TODAY },
      { id: "platform-badge", labelKey: "designSystem:sections.platformBadge.label", status: "stable", lastUpdate: TODAY },
      { id: "catalog-pagination", labelKey: "designSystem:sections.catalogPagination.label", status: "stable", lastUpdate: TODAY },
      { id: "catalog-empty-states", labelKey: "designSystem:sections.catalogEmptyStates.label", status: "stable", lastUpdate: TODAY },
      { id: "track-detail-page", labelKey: "designSystem:sections.trackDetailPage.label", status: "stable", lastUpdate: TODAY },
      { id: "similar-tracks", labelKey: "designSystem:sections.similarTracks.label", status: "stable", lastUpdate: TODAY },
      { id: "track-detail-empty-states", labelKey: "designSystem:sections.trackDetailEmptyStates.label", status: "stable", lastUpdate: TODAY },
    ],
  },
  {
    id: "notifications",
    labelKey: "designSystem:groups.notifications",
    sections: [
      { id: "toast", labelKey: "designSystem:sections.toast.label", status: "stable", lastUpdate: TODAY },
      { id: "banner", labelKey: "designSystem:sections.banner.label", status: "stable", lastUpdate: TODAY },
      { id: "modal-feedback", labelKey: "designSystem:sections.modalFeedback.label", status: "stable", lastUpdate: TODAY },
      { id: "wallet-pill", labelKey: "designSystem:sections.walletPill.label", status: "stable", lastUpdate: TODAY },
      { id: "bolsa-pill", labelKey: "designSystem:sections.bolsaPill.label", status: "stable", lastUpdate: TODAY },
      { id: "license-badge", labelKey: "designSystem:sections.licenseBadge.label", status: "stable", lastUpdate: TODAY },
      { id: "notif-tokens", labelKey: "designSystem:sections.notifTokens.label", status: "stable", lastUpdate: TODAY },
    ],
  },
];
