import type { AuditEvent } from "./types";

const HOUR = 3_600_000;
const DAY = 86_400_000;

const now = Date.now();
const ago = (ms: number) => new Date(now - ms).toISOString();

export const adminAuditMocks: AuditEvent[] = [
  {
    id: "evt-001",
    timestamp: ago(0.5 * HOUR),
    severity: "critical",
    module: "catalog",
    action: "Intento de eliminación de track con licencias activas bloqueado",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "track",
    resourceLabel: "Atardecer en Cartagena",
    resourceId: "trk-00472",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: false,
    isCritical: true,
    notes: "Se ofreció soft delete. Operación no completada.",
  },
  {
    id: "evt-002",
    timestamp: ago(2 * HOUR),
    severity: "warning",
    module: "companies",
    action: "Empresa suspendida con créditos activos",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "company",
    resourceLabel: "Postobón S.A.",
    resourceId: "co-0014",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: false,
    isCritical: true,
    diff: [
      { field: "status", before: "active", after: "suspended" },
      { field: "credits_balance", before: 1240, after: 1240 },
    ],
  },
  {
    id: "evt-003",
    timestamp: ago(5 * HOUR),
    severity: "info",
    module: "access",
    action: "Rol de usuario actualizado",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "user",
    resourceLabel: "Mariana López · Rappi Colombia",
    resourceId: "usr-0233",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
    diff: [{ field: "role", before: "Empresa User", after: "Empresa Admin" }],
  },
  {
    id: "evt-004",
    timestamp: ago(8 * HOUR),
    severity: "success",
    module: "billing",
    action: "Pago conciliado manualmente",
    actorType: "super_admin",
    actorName: "Daniel Ríos",
    actorEmail: "daniel.rios@licenciame.com",
    resourceType: "invoice",
    resourceLabel: "FAC-2026-0118 · Banco Andino",
    resourceId: "inv-2026-0118",
    ip: "186.144.21.4",
    userAgent: "Mozilla/5.0 Safari/17.4",
    sessionId: "sess-1a2b3c4d",
    reviewed: true,
    diff: [
      { field: "status", before: "pending", after: "paid" },
      { field: "reconciled_by", before: null, after: "daniel.rios@licenciame.com" },
    ],
  },
  {
    id: "evt-005",
    timestamp: ago(12 * HOUR),
    severity: "warning",
    module: "access",
    action: "MFA reseteado para usuario",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "user",
    resourceLabel: "Paula Mora · Rappi Colombia",
    resourceId: "usr-0241",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: false,
    isCritical: true,
    notes: "Solicitud verificada por canal corporativo.",
  },
  {
    id: "evt-006",
    timestamp: ago(1 * DAY),
    severity: "info",
    module: "pricing",
    action: "Paquete editado",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "package",
    resourceLabel: "Bolsa B · 2.000 créditos",
    resourceId: "pkg-b",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
    diff: [
      { field: "validity_months", before: 9, after: 12 },
      { field: "discount_pct", before: 5, after: 8 },
    ],
  },
  {
    id: "evt-007",
    timestamp: ago(1.2 * DAY),
    severity: "info",
    module: "catalog",
    action: "Track restaurado al catálogo público",
    actorType: "super_admin",
    actorName: "Daniel Ríos",
    actorEmail: "daniel.rios@licenciame.com",
    resourceType: "track",
    resourceLabel: "Lluvia en Bogotá",
    resourceId: "trk-00318",
    ip: "186.144.21.4",
    userAgent: "Mozilla/5.0 Safari/17.4",
    sessionId: "sess-1a2b3c4d",
    reviewed: true,
    diff: [{ field: "status", before: "hidden", after: "active" }],
  },
  {
    id: "evt-008",
    timestamp: ago(1.5 * DAY),
    severity: "critical",
    module: "catalog",
    action: "Track ocultado del catálogo (soft delete)",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "track",
    resourceLabel: "Verano en la ciudad",
    resourceId: "trk-00091",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: false,
    isCritical: true,
    diff: [{ field: "status", before: "active", after: "hidden" }],
    notes: "Se preserva evidencia legal. 14 licencias activas afectadas.",
  },
  {
    id: "evt-009",
    timestamp: ago(2 * DAY),
    severity: "info",
    module: "auth",
    action: "Login Super Admin exitoso",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "session",
    resourceLabel: "Sesión web · Chrome",
    resourceId: "sess-9f8e7d6c",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
  },
  {
    id: "evt-010",
    timestamp: ago(2.4 * DAY),
    severity: "warning",
    module: "auth",
    action: "5 intentos fallidos de login bloquearon cuenta",
    actorType: "system",
    actorName: "Sistema · Auth Guard",
    actorEmail: "system@licenciame.com",
    resourceType: "user",
    resourceLabel: "carlos.rios@rappi.com",
    resourceId: "usr-0237",
    ip: "45.183.99.21",
    userAgent: "curl/8.4",
    sessionId: "sys-auth-2026",
    reviewed: false,
    isCritical: true,
    notes: "IP marcada como sospechosa. Usuario notificado.",
  },
  {
    id: "evt-011",
    timestamp: ago(3 * DAY),
    severity: "success",
    module: "catalog",
    action: "Importación masiva CSV completada",
    actorType: "super_admin",
    actorName: "Daniel Ríos",
    actorEmail: "daniel.rios@licenciame.com",
    resourceType: "import_job",
    resourceLabel: "catalog_2026_q2.csv · 1.124 tracks",
    resourceId: "imp-2026-0042",
    ip: "186.144.21.4",
    userAgent: "Mozilla/5.0 Safari/17.4",
    sessionId: "sess-1a2b3c4d",
    reviewed: true,
    diff: [
      { field: "tracks_created", before: 0, after: 982 },
      { field: "tracks_updated", before: 0, after: 142 },
    ],
  },
  {
    id: "evt-012",
    timestamp: ago(3.5 * DAY),
    severity: "info",
    module: "licenses",
    action: "Licencia anulada dentro de ventana de 48h",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "license",
    resourceLabel: "LIC-K7H3-2026",
    resourceId: "lic-k7h3",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
    diff: [
      { field: "status", before: "active", after: "cancelled" },
      { field: "credits_refunded", before: 0, after: 8 },
    ],
  },
  {
    id: "evt-013",
    timestamp: ago(4 * DAY),
    severity: "warning",
    module: "billing",
    action: "Pago fallido por fondos insuficientes",
    actorType: "system",
    actorName: "Sistema · Pasarela PSE",
    actorEmail: "system@licenciame.com",
    resourceType: "invoice",
    resourceLabel: "FAC-2026-0102 · Tiendas D1",
    resourceId: "inv-2026-0102",
    ip: "—",
    userAgent: "PSE-Webhook/1.0",
    sessionId: "sys-pse-2026",
    reviewed: false,
    diff: [{ field: "status", before: "processing", after: "failed" }],
  },
  {
    id: "evt-014",
    timestamp: ago(5 * DAY),
    severity: "info",
    module: "access",
    action: "Invitación enviada",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "invitation",
    resourceLabel: "andres.quintero@bancoandino.co",
    resourceId: "inv-aq-2026",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
  },
  {
    id: "evt-015",
    timestamp: ago(6 * DAY),
    severity: "success",
    module: "companies",
    action: "Empresa reactivada",
    actorType: "super_admin",
    actorName: "Daniel Ríos",
    actorEmail: "daniel.rios@licenciame.com",
    resourceType: "company",
    resourceLabel: "Tiendas Ara",
    resourceId: "co-0008",
    ip: "186.144.21.4",
    userAgent: "Mozilla/5.0 Safari/17.4",
    sessionId: "sess-1a2b3c4d",
    reviewed: true,
    diff: [{ field: "status", before: "suspended", after: "active" }],
  },
  {
    id: "evt-016",
    timestamp: ago(7 * DAY),
    severity: "info",
    module: "system",
    action: "Exportación de bitácora generada",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "export",
    resourceLabel: "audit_2026_w16.csv",
    resourceId: "exp-w16-2026",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
  },
  {
    id: "evt-017",
    timestamp: ago(9 * DAY),
    severity: "critical",
    module: "licenses",
    action: "Disputa abierta sobre licencia",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "license",
    resourceLabel: "LIC-M2N9-2026",
    resourceId: "lic-m2n9",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: false,
    isCritical: true,
    notes: "Empresa reporta uso fuera de las condiciones. Equipo legal notificado.",
  },
  {
    id: "evt-018",
    timestamp: ago(11 * DAY),
    severity: "info",
    module: "pricing",
    action: "Plan personalizado creado para empresa",
    actorType: "super_admin",
    actorName: "Daniel Ríos",
    actorEmail: "daniel.rios@licenciame.com",
    resourceType: "custom_plan",
    resourceLabel: "Bavaria S.A. · Plan Enterprise 2026",
    resourceId: "cpl-bav-2026",
    ip: "186.144.21.4",
    userAgent: "Mozilla/5.0 Safari/17.4",
    sessionId: "sess-1a2b3c4d",
    reviewed: true,
  },
  {
    id: "evt-019",
    timestamp: ago(14 * DAY),
    severity: "success",
    module: "billing",
    action: "Nota crédito emitida",
    actorType: "super_admin",
    actorName: "Camila Soto",
    actorEmail: "camila.soto@licenciame.com",
    resourceType: "credit_note",
    resourceLabel: "NC-2026-0007 · Postobón S.A.",
    resourceId: "ncr-2026-0007",
    ip: "190.85.32.12",
    userAgent: "Mozilla/5.0 Chrome/126.0",
    sessionId: "sess-9f8e7d6c",
    reviewed: true,
    diff: [{ field: "amount_cop", before: 0, after: 4_200_000 }],
  },
  {
    id: "evt-020",
    timestamp: ago(20 * DAY),
    severity: "warning",
    module: "system",
    action: "Backup nocturno completado con advertencias",
    actorType: "system",
    actorName: "Sistema · Backup",
    actorEmail: "system@licenciame.com",
    resourceType: "backup",
    resourceLabel: "snapshot-2026-04-08-03",
    resourceId: "bk-2026-04-08",
    ip: "—",
    userAgent: "BackupAgent/2.1",
    sessionId: "sys-bk-2026",
    reviewed: true,
    notes: "Tabla licenses tardó 18% más de lo habitual.",
  },
];
