import type { AdminCompany } from "./types";

const iso = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();
const future = (daysAhead: number) => new Date(Date.now() + daysAhead * 86_400_000).toISOString();

export const adminCompaniesMocks: AdminCompany[] = [
  {
    id: "co-001",
    name: "Rappi Colombia",
    legalName: "Rappi S.A.S.",
    taxId: "900.123.456-7",
    industry: "Tecnología y delivery",
    city: "Bogotá",
    status: "active",
    plan: "bolsa-c",
    planLabel: "Bolsa C",
    joinedAt: iso(420),
    primaryContactName: "Mariana López",
    primaryContactEmail: "mariana.lopez@rappi.com",
    wallet: {
      creditsAvailable: 612,
      creditsConsumed: 388,
      creditsTotal: 1000,
      expiresAt: future(310),
      lastTopUpAt: iso(45),
    },
    activeLicenses: 24,
    monthlySpendCop: 18_400_000,
    licenses: [
      { id: "L-1001", trackTitle: "Latido Tropical", trackArtist: "Elena Cruz", status: "active", issuedAt: iso(8) },
      { id: "L-1002", trackTitle: "Sol del Caribe", trackArtist: "Luis Mar", status: "active", issuedAt: iso(15) },
      { id: "L-1003", trackTitle: "Noches de Bogotá", trackArtist: "Carla Vega", status: "consumed", issuedAt: iso(42) },
    ],
    payments: [
      { id: "P-2001", invoiceNumber: "FAC-2026-0091", amountCop: 266_000_000, status: "paid", createdAt: iso(45) },
      { id: "P-2002", invoiceNumber: "FAC-2025-0427", amountCop: 90_000_000, status: "paid", createdAt: iso(220) },
    ],
    users: [
      { id: "U-1", fullName: "Mariana López", email: "mariana.lopez@rappi.com", role: "empresa_admin", status: "active" },
      { id: "U-2", fullName: "Andrés Castro", email: "andres.castro@rappi.com", role: "empresa_user", status: "active" },
      { id: "U-3", fullName: "Paula Ruiz", email: "paula.ruiz@rappi.com", role: "empresa_user", status: "pending_mfa" },
    ],
  },
  {
    id: "co-002",
    name: "Banco Andino",
    legalName: "Banco Andino S.A.",
    taxId: "860.998.111-3",
    industry: "Servicios financieros",
    city: "Bogotá",
    status: "active",
    plan: "bolsa-b",
    planLabel: "Bolsa B",
    joinedAt: iso(280),
    primaryContactName: "Carolina Pérez",
    primaryContactEmail: "carolina.perez@bancoandino.co",
    wallet: {
      creditsAvailable: 410,
      creditsConsumed: 190,
      creditsTotal: 600,
      expiresAt: future(220),
      lastTopUpAt: iso(60),
    },
    activeLicenses: 11,
    monthlySpendCop: 8_900_000,
    licenses: [
      { id: "L-1101", trackTitle: "Confianza", trackArtist: "Dúo Norte", status: "active", issuedAt: iso(12) },
      { id: "L-1102", trackTitle: "Crecer Juntos", trackArtist: "Marina Soto", status: "active", issuedAt: iso(30) },
    ],
    payments: [
      { id: "P-2101", invoiceNumber: "FAC-2026-0072", amountCop: 166_000_000, status: "paid", createdAt: iso(60) },
    ],
    users: [
      { id: "U-10", fullName: "Carolina Pérez", email: "carolina.perez@bancoandino.co", role: "empresa_admin", status: "active" },
      { id: "U-11", fullName: "Jorge Niño", email: "jorge.nino@bancoandino.co", role: "empresa_user", status: "active" },
    ],
  },
  {
    id: "co-003",
    name: "Postobón S.A.",
    legalName: "Postobón S.A.",
    taxId: "890.903.938-8",
    industry: "Bebidas y consumo masivo",
    city: "Medellín",
    status: "overdue",
    plan: "bolsa-b",
    planLabel: "Bolsa B",
    joinedAt: iso(540),
    primaryContactName: "Felipe Arango",
    primaryContactEmail: "felipe.arango@postobon.com",
    wallet: {
      creditsAvailable: 38,
      creditsConsumed: 562,
      creditsTotal: 600,
      expiresAt: future(15),
      lastTopUpAt: iso(330),
    },
    activeLicenses: 6,
    monthlySpendCop: 4_200_000,
    licenses: [
      { id: "L-1201", trackTitle: "Refrescate", trackArtist: "Banda Río", status: "active", issuedAt: iso(70) },
    ],
    payments: [
      { id: "P-2201", invoiceNumber: "FAC-2026-0103", amountCop: 12_500_000, status: "pending", createdAt: iso(35) },
      { id: "P-2202", invoiceNumber: "FAC-2025-0309", amountCop: 166_000_000, status: "paid", createdAt: iso(330) },
    ],
    users: [
      { id: "U-20", fullName: "Felipe Arango", email: "felipe.arango@postobon.com", role: "empresa_admin", status: "active" },
    ],
  },
  {
    id: "co-004",
    name: "Tiendas D1",
    legalName: "Koba Colombia S.A.S.",
    taxId: "900.345.789-1",
    industry: "Retail",
    city: "Medellín",
    status: "active",
    plan: "bolsa-a",
    planLabel: "Bolsa A",
    joinedAt: iso(140),
    primaryContactName: "Daniela Ortiz",
    primaryContactEmail: "daniela.ortiz@tiendasd1.com",
    wallet: {
      creditsAvailable: 220,
      creditsConsumed: 80,
      creditsTotal: 300,
      expiresAt: future(360),
      lastTopUpAt: iso(20),
    },
    activeLicenses: 4,
    monthlySpendCop: 3_100_000,
    licenses: [],
    payments: [
      { id: "P-2301", invoiceNumber: "FAC-2026-0118", amountCop: 90_000_000, status: "paid", createdAt: iso(20) },
    ],
    users: [
      { id: "U-30", fullName: "Daniela Ortiz", email: "daniela.ortiz@tiendasd1.com", role: "empresa_admin", status: "active" },
      { id: "U-31", fullName: "Sergio Henao", email: "sergio.henao@tiendasd1.com", role: "empresa_user", status: "active" },
    ],
  },
  {
    id: "co-005",
    name: "Bavaria S.A.",
    legalName: "Bavaria S.A.",
    taxId: "860.005.224-6",
    industry: "Bebidas",
    city: "Bogotá",
    status: "suspended",
    plan: "bolsa-c",
    planLabel: "Bolsa C",
    joinedAt: iso(700),
    primaryContactName: "Ricardo Mejía",
    primaryContactEmail: "ricardo.mejia@bavaria.co",
    wallet: {
      creditsAvailable: 0,
      creditsConsumed: 1000,
      creditsTotal: 1000,
      expiresAt: null,
      lastTopUpAt: iso(540),
    },
    activeLicenses: 0,
    monthlySpendCop: 0,
    licenses: [
      { id: "L-1301", trackTitle: "Brindemos", trackArtist: "Andrés Cabas", status: "expired", issuedAt: iso(540) },
    ],
    payments: [
      { id: "P-2401", invoiceNumber: "FAC-2024-0987", amountCop: 266_000_000, status: "paid", createdAt: iso(540) },
    ],
    users: [
      { id: "U-40", fullName: "Ricardo Mejía", email: "ricardo.mejia@bavaria.co", role: "empresa_admin", status: "suspended" },
    ],
  },
  {
    id: "co-006",
    name: "Grupo Éxito",
    legalName: "Almacenes Éxito S.A.",
    taxId: "890.900.608-9",
    industry: "Retail",
    city: "Envigado",
    status: "active",
    plan: "custom",
    planLabel: "Personalizado · 1.500 créditos",
    joinedAt: iso(95),
    primaryContactName: "Tatiana Gómez",
    primaryContactEmail: "tatiana.gomez@grupoexito.com",
    wallet: {
      creditsAvailable: 1340,
      creditsConsumed: 160,
      creditsTotal: 1500,
      expiresAt: future(450),
      lastTopUpAt: iso(10),
    },
    activeLicenses: 9,
    monthlySpendCop: 6_700_000,
    licenses: [
      { id: "L-1401", trackTitle: "Color Local", trackArtist: "Trío Andino", status: "active", issuedAt: iso(5) },
    ],
    payments: [
      { id: "P-2501", invoiceNumber: "FAC-2026-0140", amountCop: 380_000_000, status: "paid", createdAt: iso(10) },
    ],
    users: [
      { id: "U-50", fullName: "Tatiana Gómez", email: "tatiana.gomez@grupoexito.com", role: "empresa_admin", status: "active" },
      { id: "U-51", fullName: "Marcela Vélez", email: "marcela.velez@grupoexito.com", role: "empresa_user", status: "active" },
      { id: "U-52", fullName: "Camilo Rivas", email: "camilo.rivas@grupoexito.com", role: "empresa_user", status: "active" },
    ],
  },
];
