"""add_engagement_stats_to_external_contents

Revision ID: 1c427d743149
Revises: 
Create Date: 2026-03-24 23:51:26.599754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c427d743149'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_contents', sa.Column('views', sa.BigInteger(), nullable=True))
    op.add_column('external_contents', sa.Column('likes', sa.BigInteger(), nullable=True))
    op.add_column('external_contents', sa.Column('comments', sa.BigInteger(), nullable=True))
    op.add_column('external_contents', sa.Column('shares', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_contents', 'shares')
    op.drop_column('external_contents', 'comments')
    op.drop_column('external_contents', 'likes')
    op.drop_column('external_contents', 'views')
    # ### end Alembic commands ###
