/** All UI strings for F-04 — Spanish only. Code stays English. */
export const packagesStrings = {
  page: {
    title: "Comprar créditos",
    subtitle: "Bolsas corporativas para licenciar música.",
    historyCta: "Ver historial de compras",
    backToPackages: "Volver a paquetes",
  },
  walletSummary: {
    title: "Tu wallet",
    creditsAvailable: "{count} créditos disponibles",
    activeBags: "{count} bolsa activa",
    activeBagsPlural: "{count} bolsas activas",
    earliestExpiry: "Próxima en vencer: {when} ({bagName} · {remaining}/{total})",
    noActiveBags: "No tienes bolsas activas. Compra tu primera bolsa para licenciar música.",
    loadingError: "No pudimos cargar tu wallet. Intenta nuevamente.",
    retry: "Reintentar",
  },
  packageCard: {
    creditsLabel: "créditos",
    validityLabel: "Vigencia: {months} meses",
    pricePerCredit: "${value} COP por crédito",
    buyCta: "Comprar",
    recommended: "Más popular",
    bestRatio: "Mejor relación crédito/COP",
    pricePerCreditTooltip:
      "Precio por crédito calculado: ${total} COP ÷ {credits} créditos = ${perCredit} COP/crédito.",
  },
  comparisonTable: {
    title: "Tabla comparativa",
    expand: "Ver tabla comparativa",
    collapse: "Ocultar tabla",
    columns: {
      package: "Paquete",
      credits: "Créditos",
      price: "Precio (COP)",
      validity: "Vigencia",
      pricePerCredit: "Precio por crédito",
    },
    monthsSuffix: "meses",
  },
  activeBags: {
    title: "Bolsas activas",
    subtitle: "Las bolsas se acumulan. El consumo es FIFO: primero se usan los créditos de la bolsa que vence antes.",
    emptyTitle: "No tienes bolsas activas",
    emptyDescription: "Compra una bolsa para empezar a licenciar.",
    bagRemaining: "{remaining} de {total} créditos disponibles",
    expiresIn: "Vence en {days} días",
    expiresOn: "Vence el {date}",
    nextToConsume: "Próxima en consumirse",
    statusActive: "Activa",
    statusExhausted: "Consumida",
    statusExpired: "Expirada",
  },
  purchaseDialog: {
    title: "Comprar {packageName}",
    closeAria: "Cerrar diálogo",
    backAria: "Atrás",
    steps: {
      review: "Revisar cotización",
      method: "Método de pago",
      card: "Datos de tarjeta",
      processing: "Procesando…",
      bankTransfer: "Transferencia bancaria",
      success: "Compra confirmada",
      failed: "No se pudo procesar",
    },
    review: {
      packageBlock: "Paquete",
      conceptCredits: "{credits} créditos · vigencia {months} meses",
      breakdown: "Desglose",
      subtotal: "Subtotal",
      iva: "IVA 19% (simulado)",
      ivaTooltip: "Cálculo demo. Sin valor fiscal hasta integración real con DIAN.",
      total: "Total",
      validUntil: "Cotización válida hasta el {date}.",
      downloadQuote: "Descargar cotización PDF",
      cancel: "Cancelar",
      continue: "Continuar al pago",
    },
    method: {
      legend: "Selecciona un método de pago",
      card: "Tarjeta de crédito (simulada)",
      cardDescription: "Aprobación inmediata en pantalla.",
      bank: "Transferencia bancaria (simulada)",
      bankDescription: "Te entregamos los datos para hacer el depósito.",
      disclaimer: "Ambos métodos son simulaciones. No se procesará ningún cobro real.",
      back: "Atrás",
      continue: "Continuar",
    },
    card: {
      cardholderLabel: "Nombre del titular",
      cardholderPlaceholder: "Como aparece en la tarjeta",
      numberLabel: "Número de tarjeta",
      numberPlaceholder: "0000 0000 0000 0000",
      numberHint: "Usa cualquier número de 16 dígitos. Ej: 4111 1111 1111 1111",
      expiryMonthLabel: "Mes",
      expiryYearLabel: "Año",
      cvvLabel: "CVV",
      forceFailure: "Forzar rechazo (modo dev)",
      back: "Atrás",
      pay: "Pagar ${total} COP",
      errors: {
        cardholder: "Ingresa el nombre del titular.",
        number: "Debe tener 16 dígitos.",
        expiryMonth: "Mes inválido.",
        expiryYear: "Año inválido.",
        cvv: "CVV de 3 dígitos.",
        expired: "La tarjeta está vencida.",
      },
    },
    processing: {
      title: "Procesando pago…",
      description: "Estamos validando tu transacción. No cierres esta ventana.",
    },
    bankTransfer: {
      title: "Datos para tu transferencia",
      description: "Realiza la transferencia con la referencia exacta para que podamos identificarla.",
      bank: "Banco",
      accountType: "Tipo de cuenta",
      accountNumber: "Número de cuenta",
      accountHolder: "Titular",
      nit: "NIT",
      reference: "Referencia",
      amount: "Monto exacto",
      expiresAt: "Vence: {date}",
      copy: "Copiar",
      copied: "Copiado",
      disclaimer: "Esta es una transferencia simulada. Los datos son ficticios y no debes hacer un giro real.",
      done: "Entendido, ir a mis compras",
      devConfirm: "🧪 Simular pago recibido",
    },
    success: {
      title: "¡Compra confirmada!",
      description: "Acreditamos {credits} créditos a tu cuenta. Vigencia hasta el {date}.",
      downloadReceipt: "Descargar recibo provisional",
      goToCatalog: "Ir a comprar música",
      close: "Cerrar",
      toast: "Saldo actualizado: {balance} créditos.",
    },
    failed: {
      title: "No pudimos procesar tu pago",
      defaultReason: "Intenta de nuevo en unos minutos.",
      reasons: {
        PAYMENT_DECLINED: "Tu banco rechazó la transacción. Intenta con otra tarjeta.",
        CARD_INVALID: "Los datos de la tarjeta no son válidos.",
        QUOTE_EXPIRED: "La cotización venció. Genera una nueva para continuar.",
        NETWORK_ERROR: "Hubo un problema de conexión. Intenta de nuevo.",
      },
      cancel: "Cancelar",
      retry: "Reintentar",
    },
  },
  history: {
    title: "Historial de compras",
    subtitle: "Todas tus transacciones, confirmadas y pendientes.",
    backToPackages: "Volver a paquetes",
    columns: {
      date: "Fecha",
      package: "Paquete",
      credits: "Créditos",
      creditsCredited: "Acreditados",
      method: "Método",
      status: "Estado",
      total: "Total",
      actions: "Acciones",
    },
    methods: {
      "card-simulated": "Tarjeta",
      "bank-transfer-simulated": "Transferencia",
    },
    statuses: {
      draft: "Borrador",
      processing: "Procesando",
      pending: "Pendiente",
      pending_payment: "Pendiente de pago",
      pending_confirmation: "En conciliación",
      confirmed: "Confirmada",
      failed: "Fallida",
      rejected: "Rechazada",
      manual_review: "En revisión",
      expired: "Expirada",
    },
    statusAria: "Estado: {label}",
    viewDetail: "Ver detalle",
    quickView: "Vista rápida",
    downloadReceipt: "Descargar recibo",
    creditsHeld: "0 acreditados — el pago está pendiente.",
    creditsHeldShort: "Retenidos",
    pagination: {
      previous: "Anterior",
      next: "Siguiente",
      page: "Página {current} de {total}",
    },
    empty: {
      title: "Aún no tienes compras",
      description: "Cuando hagas tu primera compra, la verás aquí.",
      cta: "Ver paquetes",
    },
    error: "No pudimos cargar el historial.",
    retry: "Reintentar",
    loading: "Cargando historial…",
    filters: {
      legend: "Filtrar por estado",
      all: "Todas",
      confirmed: "Confirmadas",
      pending: "Pendientes",
      review: "En revisión",
      rejected: "Rechazadas",
      clear: "Limpiar filtros",
      emptyResult: "No hay órdenes con ese estado.",
    },
    receiptDownloadedToast: "Recibo descargado.",
  },
  timeline: {
    title: "Línea de tiempo",
    subtitle: "Trazabilidad completa de la orden.",
    empty: "No hay eventos registrados todavía.",
    actor: {
      system: "Sistema",
      user: "Usuario",
      ops: "Operaciones",
    },
    events: {
      order_created: "Orden creada",
      quote_generated: "Cotización generada",
      payment_initiated: "Pago iniciado",
      payment_pending: "Pago en espera",
      payment_received: "Pago recibido",
      payment_rejected: "Pago rechazado",
      manual_review_flagged: "Marcada para revisión manual",
      credits_credited: "Créditos acreditados",
      receipt_emitted: "Recibo emitido",
      confirmation_email_sent: "Correo de confirmación enviado",
    },
  },
  provisional: {
    label: "Documento provisional · no fiscal",
    tooltip:
      "Este recibo es para fines de control interno. La factura electrónica DIAN se emitirá cuando exista la integración tributaria correspondiente.",
  },
  support: {
    corporate: {
      title: "¿Necesitas ayuda con esta compra?",
      body: "Nuestro equipo de cuentas corporativas está disponible para acompañarte en pagos de alto monto, conciliación o revisión.",
      email: "cuentas@licenciame.app",
      phone: "+57 601 555 0199",
      hours: "Lunes a viernes · 8:00 a.m. - 6:00 p.m. (COT)",
      ctaEmail: "Escribir al equipo",
      ctaPhone: "Llamar",
    },
  },
  edgeCases: {
    duplicateCharge: {
      title: "Posible doble cobro detectado",
      body: "Detectamos otra orden confirmada con la misma cotización. Contáctanos para revisarlo.",
      cta: "Contactar soporte",
      chip: "duplicate-suspect",
    },
    confirmationDelay: {
      title: "Tu pago está en revisión",
      body: "Han pasado más de 24 horas desde que recibimos el pago. Estamos validando la conciliación bancaria. Te avisaremos por correo en cuanto se acrediten los créditos.",
    },
    bagExpiredDuringPurchase: {
      title: "Bolsa anterior expiró durante el procesamiento",
      body: "Mientras se procesaba esta compra, una bolsa anterior alcanzó su fecha de vencimiento. Tus créditos nuevos están intactos y disponibles.",
    },
  },
  drawer: {
    aria: "Detalle rápido de compra",
    sections: {
      summary: "Resumen",
      reason: "Motivo",
      timeline: "Línea de tiempo",
      documents: "Documentos",
      support: "Soporte",
    },
    reasonDefault: {
      rejected: "El pago fue rechazado. Puedes reintentar con otro método o contactar a soporte.",
      failed: "No pudimos procesar el pago. Reintenta o contacta a soporte.",
      pending_confirmation: "Estamos validando tu transferencia. Te avisaremos cuando se acrediten los créditos.",
      manual_review: "Esta orden está en revisión manual por parte del equipo de cuentas.",
    },
    actions: {
      retry: "Reintentar pago",
      contactSupport: "Contactar soporte",
    },
    close: "Cerrar",
    fullDetail: "Ver detalle completo",
  },
  lowBalanceBanner: {
    title: "Tu saldo está bajo",
    body: "Tienes {count} créditos disponibles. Recarga tu wallet antes de quedarte sin créditos para licenciar.",
    cta: "Recargar wallet",
    dismissAria: "Ocultar aviso de saldo bajo",
  },
  detail: {
    breadcrumb: "Historial",
    title: "Compra {id}",
    notFoundTitle: "Compra no encontrada",
    notFoundDescription: "La compra que buscas no existe o fue removida.",
    back: "Volver al historial",
    summaryTitle: "Resumen del paquete",
    breakdown: "Desglose",
    subtotal: "Subtotal",
    iva: "IVA 19% (simulado)",
    total: "Total",
    timeline: {
      title: "Línea de tiempo",
      created: "Cotización creada",
      paymentStartedCard: "Pago iniciado (tarjeta)",
      paymentStartedTransfer: "Pago iniciado (transferencia)",
      confirmed: "Compra confirmada",
      failed: "Pago fallido",
      pending: "En espera de transferencia",
    },
    paymentMethod: {
      title: "Método de pago",
      card: "Tarjeta terminada en {last4}",
      transfer: "Transferencia · referencia {reference}",
    },
    documents: {
      title: "Documentos",
      quote: "Descargar cotización",
      receipt: "Descargar recibo provisional",
      receiptNotAvailable: "El recibo se habilita cuando la compra esté confirmada.",
    },
    failedReason: "Razón: {reason}",
    retryPurchase: "Comprar de nuevo",
    pendingDevConfirm: "🧪 Simular pago recibido",
  },
  demoNotice: {
    quote: "Documento provisional para demostración. Sin valor legal ni fiscal hasta integración real con DIAN.",
    receipt: "Documento provisional. No es una factura electrónica DIAN. Cuando se integre la facturación real, este recibo será reemplazado.",
    pageBanner: "Esta es una demo: ningún pago se procesa de verdad y los documentos no tienen valor fiscal.",
  },
  pdf: {
    quoteTitle: "COTIZACIÓN",
    receiptTitle: "RECIBO DE COMPRA — DEMO",
    quoteNumberLabel: "N° cotización",
    receiptNumberLabel: "N° recibo",
    issuedAtLabel: "Fecha de emisión",
    validUntilLabel: "Válida hasta",
    confirmedAtLabel: "Fecha de confirmación",
    buyerSection: "Comprador",
    conceptSection: "Concepto",
    paymentSection: "Pago",
    cardLabel: "Tarjeta terminada en {last4}",
    transferLabel: "Transferencia · ref. {reference}",
    columns: {
      description: "Descripción",
      credits: "Créditos",
      validity: "Vigencia (meses)",
      unitPrice: "Valor unitario",
    },
    subtotal: "Subtotal",
    iva: "IVA 19% (simulado, sin valor fiscal)",
    total: "TOTAL (COP)",
    quoteFooter: "DOCUMENTO PROVISIONAL DEMO · Sin valor legal ni fiscal · Generado para fines de demostración del MVP.",
    receiptFooter: "DOCUMENTO PROVISIONAL DEMO · Esto NO es una factura electrónica DIAN. Cuando se integre la facturación real, este recibo será reemplazado por una factura válida.",
    website: "licenciame.app",
  },
  fifo: {
    chip: "Próxima en consumirse",
  },
  checkout: {
    breadcrumb: "Volver a Wallet",
    title: "Comprar créditos",
    subtitle: "Wizard corporativo · 5 pasos · pago simulado.",
    back: "Atrás",
    continue: "Continuar",
    confirm: "Confirmar y pagar",
    resumeBanner: "Continuamos donde lo dejaste.",
    resetAll: "Empezar de nuevo",
    stepper: {
      aria: "Pasos del checkout",
      step1: "Paquete",
      step2: "Facturación",
      step3: "Pago",
      step4: "Resumen",
      step5: "Resultado",
    },
    summary: {
      aria: "Resumen de compra",
      title: "Resumen",
      emptyPackage: "Selecciona un paquete para ver el resumen.",
      creditsSuffix: "créditos",
      validity: "vigencia {months} meses",
      subtotal: "Subtotal",
      iva: "IVA 19% (simulado)",
      total: "Total",
      billingTitle: "Facturación",
      methodTitle: "Método de pago",
      accumulationFirst: "Esta será tu primera bolsa activa.",
      accumulationActive:
        "Esta compra se sumará a tus {count} bolsa(s) activa(s).",
      fifo: "Consumo FIFO: primero se usan los créditos de la bolsa que vence antes.",
    },
    method: {
      card: "Tarjeta de crédito (simulada)",
      bank: "Transferencia bancaria (simulada)",
    },
    step1Body: {
      title: "Selecciona tu paquete",
      subtitle: "Las bolsas se acumulan. El consumo es FIFO.",
      selectCta: "Seleccionar",
      selectedCta: "Seleccionado",
      error: "No pudimos cargar los paquetes. Intenta nuevamente.",
      accumulationBanner:
        "Ya tienes {count} bolsa(s) activa(s). Esta compra se sumará a tu wallet, no la reemplaza.",
    },
    step2: {
      title: "Datos de facturación",
      subtitle:
        "Necesitamos estos datos para emitir la cotización y el recibo demo.",
      submit: "Guardar y continuar",
      saveError: "No pudimos guardar tu perfil. Intenta de nuevo.",
      fields: {
        legalName: "Razón social",
        taxId: "NIT",
        taxpayerType: "Tipo de persona",
        taxRegime: "Régimen tributario",
        billingEmail: "Correo de facturación",
        fiscalAddress: "Dirección fiscal",
        city: "Ciudad",
        country: "País",
        contactName: "Nombre del contacto",
        contactPhone: "Teléfono del contacto",
      },
      placeholders: {
        legalName: "Marca Demo S.A.S.",
        billingEmail: "compras@empresa.co",
        fiscalAddress: "Calle 93 # 11-13, Oficina 502",
        city: "Bogotá D.C.",
        contactName: "Andrea Vargas",
        cardholder: "Como aparece en la tarjeta",
      },
      hints: {
        taxId: "Formato: 900.123.456-7",
      },
      taxpayerTypes: {
        natural: "Persona natural",
        juridica: "Persona jurídica",
      },
      taxRegimes: {
        "responsable-iva": "Responsable de IVA",
        "no-responsable-iva": "No responsable de IVA",
        "regimen-simple": "Régimen simple de tributación",
        "gran-contribuyente": "Gran contribuyente",
      },
      countries: {
        COL: "Colombia",
        MEX: "México",
        ARG: "Argentina",
        CHL: "Chile",
        PER: "Perú",
      },
      errors: {
        required: "Este campo es obligatorio.",
        legalName: "Ingresa la razón social (3-200 caracteres).",
        taxId: "Formato NIT inválido. Ej: 900.123.456-7",
        email: "Correo electrónico inválido.",
        fiscalAddress: "Ingresa la dirección fiscal (5-200 caracteres).",
        city: "Ingresa la ciudad.",
        contactName: "Ingresa el nombre del contacto.",
        contactPhone: "Teléfono inválido. Ej: +57 3001234567",
      },
    },
    step3: {
      title: "Método de pago",
      subtitle: "Ambos métodos son simulaciones. No se procesa cobro real.",
      legend: "Selecciona un método de pago",
      card: "Tarjeta de crédito (simulada)",
      cardDescription: "Aprobación inmediata en pantalla.",
      bank: "Transferencia bancaria (simulada)",
      bankDescription:
        "Te entregamos los datos para que hagas la transferencia.",
      cardFormTitle: "Datos de la tarjeta",
      numberHint: "Usa cualquier número de 16 dígitos. Ej: 4111 1111 1111 1111",
      forceFailure: "Forzar rechazo (modo dev)",
      transferPreviewTitle: "Recibirás los datos para transferir",
      transferPreview:
        "Banco Demo S.A. · cuenta corriente · referencia única generada al confirmar. Plazo sugerido: 72h.",
      fields: {
        cardholder: "Nombre del titular",
        number: "Número de tarjeta",
        expiryMonth: "Mes",
        expiryYear: "Año",
        cvv: "CVV",
      },
      placeholders: {
        cardholder: "Como aparece en la tarjeta",
      },
      errors: {
        cardholder: "Ingresa el nombre del titular.",
        number: "Debe tener 16 dígitos.",
        expiryMonth: "Mes inválido (01-12).",
        expiryYear: "Año inválido (2 dígitos).",
        cvv: "CVV de 3 dígitos.",
      },
    },
    step4: {
      title: "Revisa tu compra",
      subtitle:
        "Verifica el desglose y acepta los términos para confirmar el pago.",
      packageBlock: "Paquete",
      creditsLine: "{credits} créditos · vigencia {months} meses",
      loadingQuote: "Generando cotización…",
      quoteError: "No pudimos generar la cotización.",
      retry: "Reintentar",
      subtotal: "Subtotal",
      iva: "IVA 19% (simulado)",
      ivaTooltip:
        "Cálculo demo. Sin valor fiscal hasta integración real con DIAN.",
      total: "Total",
      validUntil: "Cotización válida hasta el {date}.",
      billingTitle: "Facturación",
      methodTitle: "Método de pago",
      edit: "Editar",
      downloadQuote: "Descargar cotización PDF",
      downloadSuccess: "Cotización descargada.",
      terms:
        "He leído y acepto los términos de uso y la política de facturación demo.",
      termsLink: "Ver términos",
    },
    step5: {
      processing: {
        title: "Procesando pago…",
        description:
          "Estamos validando tu transacción. No cierres esta ventana.",
      },
      approved: {
        title: "¡Compra confirmada!",
        description:
          "Acreditamos {credits} créditos a tu cuenta. Saldo actual: {balance} créditos.",
        toast: "Saldo actualizado: +{credits} créditos.",
        downloadReceipt: "Descargar recibo",
        goToWallet: "Ir a mi wallet",
        goToCatalog: "Ir a comprar música",
      },
      pending: {
        title: "Pago pendiente — Transferencia bancaria",
        subtitle:
          "Realiza la transferencia con la referencia exacta para que podamos identificarla.",
        toast: "Compra creada en estado pendiente.",
        disclosure:
          "Los créditos se acreditarán cuando confirmemos la transferencia. Te enviaremos un correo a {email}.",
        copy: "Copiar",
        downloadInstructions: "Descargar instrucciones",
        goToHistory: "Ir a mis compras",
        devConfirm: "🧪 Simular pago recibido",
        fields: {
          bank: "Banco",
          accountType: "Tipo de cuenta",
          accountNumber: "Número de cuenta",
          holder: "Titular",
          nit: "NIT",
          reference: "Referencia",
          amount: "Monto exacto",
          expiresAt: "Vence",
        },
      },
      rejected: {
        title: "No pudimos procesar tu pago",
        retry: "Reintentar con otra tarjeta",
        changeMethod: "Cambiar a transferencia",
      },
      networkError: {
        title: "Problema de conexión",
        description:
          "Hubo un problema de conexión. Tu compra no se procesó.",
        retry: "Reintentar",
        backToReview: "Volver al resumen",
      },
    },
  },
  walletHub: {
    eyebrow: "Wallet · Créditos corporativos",
    title: "Wallet",
    subtitle: "Créditos corporativos para licenciar música.",
    hubBadge: "Vista hub",
    sectionOverview: "Resumen",
    sectionActiveBags: "Bolsas activas",
    sectionRecent: "Últimas compras",
    sectionMorePackages: "Comprar más créditos",
    sectionMorePackagesSub:
      "Acumula bolsas. Las nuevas se suman a las activas y se consumen FIFO.",
    tocLabel: "Navegación de la página Wallet",
    tocOverview: "Resumen",
    tocActiveBags: "Bolsas activas",
    tocPurchases: "Últimas compras",
    tocPackages: "Comprar más",
    kpis: {
      balance: "Saldo disponible",
      balanceUnit: "créditos",
      consumed: "Créditos consumidos",
      consumedHint: "Histórico de la empresa",
      purchased: "Créditos comprados",
      purchasedHint: "Histórico de la empresa",
      nextExpiry: "Próxima vigencia",
      nextExpiryUnit: "meses",
      nextExpiryNone: "Sin bolsas activas",
      activeBags: "{count} bolsa activa",
      activeBagsPlural: "{count} bolsas activas",
      error: "No pudimos cargar los KPIs.",
      retry: "Reintentar",
    },
    fifoExplainer: {
      title: "¿Cómo se consumen tus créditos?",
      body: "Tus créditos se consumen primero de la bolsa que vence antes. Así evitas que expiren créditos sin usar.",
      stepNew: "Bolsa nueva",
      stepActive: "Bolsa activa",
      stepNext: "Próxima en consumirse",
    },
    lowBalance: {
      title: "Saldo bajo",
      body: "Tienes {count} créditos disponibles. Considera recargar antes de quedarte sin créditos para licenciar.",
      cta: "Recargar wallet",
    },
    buyCta: {
      title: "Recarga tu wallet",
      body: "Compra una bolsa nueva. Las bolsas se acumulan y se consumen FIFO.",
      primary: "Recargar wallet",
      recommendedTag: "Recomendado",
    },
    recent: {
      title: "Últimas compras",
      subtitle: "Las 3 transacciones más recientes de tu empresa.",
      viewAll: "Ver historial completo",
      emptyTitle: "Aún no tienes compras",
      emptyDescription: "Cuando hagas tu primera compra, la verás aquí.",
      emptyCta: "Recargar wallet",
      error: "No pudimos cargar las últimas compras.",
      retry: "Reintentar",
      rowAria: "Ver detalle de compra {id}",
      reasonAria: "Motivo: {reason}",
    },
  },
};

/** Replace {token} placeholders with values. */
export function formatString(
  template: string,
  vars: Record<string, string | number>,
): string {
  return Object.entries(vars).reduce(
    (acc, [k, v]) => acc.split(`{${k}}`).join(String(v)),
    template,
  );
}
