import type { AlternativeTrack, UnifiedMatchRow } from "./types.unified";

export const unifiedMatchRows: UnifiedMatchRow[] = [
  {
    id: "u_01",
    externalTitle: "Midnight Pulse",
    externalArtist: "Nova Lane",
    externalAlbum: "Pulse EP",
    externalDuration: "3:24",
    externalMetadata: "ISRC · BPM · Género",
    source: "spotify",
    catalogTitle: "Midnight Pulse",
    catalogArtist: "Nova Lane",
    catalogVersion: "Original",
    catalogDuration: "3:24",
    matchType: "exact",
    confidence: 98,
    credits: 4,
    status: "matched",
    licenseStatus: "not_licensed",
  },
  {
    id: "u_02",
    externalTitle: "Corporate Motion",
    externalArtist: "SoundLab",
    externalAlbum: "Brand Tracks Vol. 3",
    externalDuration: "2:48",
    externalMetadata: "ISRC · Género",
    source: "meta",
    catalogTitle: "Corporate Motion",
    catalogArtist: "SoundLab",
    catalogVersion: "Original",
    catalogDuration: "2:48",
    matchType: "exact",
    confidence: 96,
    credits: 3,
    status: "already_licensed",
    licenseStatus: "licensed",
    legalNote: "Licencia LIC-A12-2026 vigente.",
  },
  {
    id: "u_03",
    externalTitle: "Golden Reels Remix",
    externalArtist: "Marea",
    externalAlbum: "Golden Reels (Remixes)",
    externalDuration: "3:52",
    externalMetadata: "Género · BPM",
    source: "tiktok",
    catalogTitle: "Golden Reels",
    catalogArtist: "Marea",
    catalogVersion: "Original Studio",
    catalogDuration: "3:18",
    matchType: "partial",
    confidence: 72,
    credits: 5,
    status: "partial",
    licenseStatus: "pending",
  },
  {
    id: "u_04",
    externalTitle: "Soft Horizon Live",
    externalArtist: "Ana Field",
    externalAlbum: "Live at Bogotá",
    externalDuration: "4:10",
    externalMetadata: "Género",
    source: "spotify",
    catalogTitle: "Soft Horizon",
    catalogArtist: "Ana Field",
    catalogVersion: "Studio",
    catalogDuration: "3:55",
    matchType: "partial",
    confidence: 68,
    credits: 4,
    status: "partial",
    licenseStatus: "not_licensed",
  },
  {
    id: "u_05",
    externalTitle: "City Lights",
    externalArtist: "Orion Club",
    externalAlbum: "Night Drive",
    externalDuration: "3:01",
    source: "tiktok",
    matchType: "none",
    confidence: 0,
    status: "not_available",
    licenseStatus: "not_licensed",
  },
  {
    id: "u_06",
    externalTitle: "Event Drive",
    externalArtist: "Pulse Unit",
    externalAlbum: "Pulse Unit Vol. 2",
    externalDuration: "2:36",
    source: "meta",
    catalogTitle: "Event Drive",
    catalogArtist: "Pulse Unit",
    catalogVersion: "Pendiente verificación",
    catalogDuration: "2:36",
    matchType: "legal_review",
    confidence: 61,
    credits: 4,
    status: "partial",
    licenseStatus: "pending",
    legalNote: "En revisión por equipo legal.",
  },
  {
    id: "u_07",
    externalTitle: "Sunset Loop",
    externalArtist: "Marea",
    externalAlbum: "Loops Vol. 1",
    externalDuration: "2:20",
    source: "spotify",
    matchType: "title_artist",
    confidence: 88,
    catalogTitle: "Sunset Loop",
    catalogArtist: "Marea",
    catalogVersion: "Original",
    catalogDuration: "2:20",
    credits: 3,
    status: "matched",
    licenseStatus: "not_licensed",
  },
  {
    id: "u_08",
    externalTitle: "Trending Beat",
    externalArtist: "Unknown",
    source: "tiktok",
    matchType: "none",
    confidence: 0,
    status: "not_available",
    licenseStatus: "not_licensed",
  },
];

export const alternativeTracks: AlternativeTrack[] = [
  { id: "alt_01", title: "Corporate Motion", artist: "SoundLab", mood: "Corporate · Uplifting", credits: 3 },
  { id: "alt_02", title: "Creator Spark", artist: "Lumen Co.", mood: "Energetic · Pop", credits: 4 },
  { id: "alt_03", title: "Soft Horizon", artist: "Ana Field", mood: "Chill · Ambient", credits: 4 },
];
