import type { AdminPayment, PaymentTimelineEvent } from "./types";

const HOUR = 3_600_000;
const DAY = 86_400_000;
const now = Date.now();
const ago = (ms: number) => new Date(now - ms).toISOString();

function tl(...e: PaymentTimelineEvent[]): PaymentTimelineEvent[] {
  return e;
}

export const adminBillingMocks: AdminPayment[] = [
  {
    id: "pay-001",
    invoiceNumber: "FAC-2026-0118",
    companyId: "co-0002",
    companyName: "Banco Andino",
    companyTaxId: "NIT 860.034.917-1",
    companyAddress: "Av. El Dorado #69-76, Bogotá",
    packageName: "Bolsa B · 2.000 créditos",
    creditsPurchased: 2000,
    amountSubtotalCop: 139_495_798,
    amountIvaCop: 26_504_202,
    amountTotalCop: 166_000_000,
    method: "pse",
    status: "paid",
    bankReference: "PSE-202604-118-89421",
    createdAt: ago(8 * HOUR + 30 * 60_000),
    paidAt: ago(8 * HOUR),
    reconciledByName: "Daniel Ríos",
    timeline: tl(
      {
        id: "tl-1-1",
        timestamp: ago(8 * HOUR + 30 * 60_000),
        type: "created",
        title: "Factura creada",
        description: "Generada desde el flujo de checkout.",
        actor: "Banco Andino",
      },
      {
        id: "tl-1-2",
        timestamp: ago(8 * HOUR + 20 * 60_000),
        type: "processing",
        title: "Redirección a PSE",
        description: "Cliente confirmó el pago.",
      },
      {
        id: "tl-1-3",
        timestamp: ago(8 * HOUR),
        type: "paid",
        title: "Pago confirmado",
        description: "Webhook PSE recibido.",
      },
      {
        id: "tl-1-4",
        timestamp: ago(7 * HOUR),
        type: "reconciled",
        title: "Conciliación contable",
        description: "Validado contra extracto bancario.",
        actor: "Daniel Ríos",
      },
    ),
  },
  {
    id: "pay-002",
    invoiceNumber: "FAC-2026-0117",
    companyId: "co-0001",
    companyName: "Rappi Colombia",
    companyTaxId: "NIT 901.054.391-7",
    companyAddress: "Cl. 93 #19-58, Bogotá",
    packageName: "Bolsa C · 4.000 créditos",
    creditsPurchased: 4000,
    amountSubtotalCop: 223_529_412,
    amountIvaCop: 42_470_588,
    amountTotalCop: 266_000_000,
    method: "transfer",
    status: "pending",
    bankReference: "TRF-BANCOLOMBIA-7711",
    createdAt: ago(1 * DAY),
    paidAt: null,
    timeline: tl({
      id: "tl-2-1",
      timestamp: ago(1 * DAY),
      type: "created",
      title: "Factura creada",
      description: "Cliente eligió pago por transferencia.",
    }),
  },
  {
    id: "pay-003",
    invoiceNumber: "FAC-2026-0102",
    companyId: "co-0004",
    companyName: "Tiendas D1",
    companyTaxId: "NIT 900.380.835-3",
    companyAddress: "Cl. 17 #43F-138, Medellín",
    packageName: "Bolsa A · 1.000 créditos",
    creditsPurchased: 1000,
    amountSubtotalCop: 75_630_252,
    amountIvaCop: 14_369_748,
    amountTotalCop: 90_000_000,
    method: "pse",
    status: "failed",
    bankReference: "PSE-202604-102-44012",
    errorReason: "insufficient_funds",
    createdAt: ago(4 * DAY),
    paidAt: null,
    timeline: tl(
      {
        id: "tl-3-1",
        timestamp: ago(4 * DAY),
        type: "created",
        title: "Factura creada",
      },
      {
        id: "tl-3-2",
        timestamp: ago(4 * DAY - 5 * 60_000),
        type: "processing",
        title: "Pago en proceso",
        description: "Redirigido a PSE.",
      },
      {
        id: "tl-3-3",
        timestamp: ago(4 * DAY - 8 * 60_000),
        type: "failed",
        title: "Pago fallido",
        description: "Banco emisor reportó fondos insuficientes.",
      },
    ),
  },
  {
    id: "pay-004",
    invoiceNumber: "FAC-2026-0099",
    companyId: "co-0007",
    companyName: "Grupo Éxito",
    companyTaxId: "NIT 890.900.608-9",
    companyAddress: "Cra. 48 #32B Sur-139, Envigado",
    packageName: "Bolsa B · 2.000 créditos",
    creditsPurchased: 2000,
    amountSubtotalCop: 139_495_798,
    amountIvaCop: 26_504_202,
    amountTotalCop: 166_000_000,
    method: "card",
    status: "paid",
    bankReference: "AUTH-VISA-4421-9988",
    createdAt: ago(6 * DAY),
    paidAt: ago(6 * DAY),
    reconciledByName: "Camila Soto",
    timeline: tl(
      { id: "tl-4-1", timestamp: ago(6 * DAY), type: "created", title: "Factura creada" },
      { id: "tl-4-2", timestamp: ago(6 * DAY), type: "paid", title: "Pago confirmado" },
      {
        id: "tl-4-3",
        timestamp: ago(5 * DAY),
        type: "reconciled",
        title: "Conciliación",
        actor: "Camila Soto",
      },
    ),
  },
  {
    id: "pay-005",
    invoiceNumber: "FAC-2026-0088",
    companyId: "co-0014",
    companyName: "Postobón S.A.",
    companyTaxId: "NIT 890.903.939-5",
    companyAddress: "Cra. 50 #1Sur-200, Medellín",
    packageName: "Bolsa A · 1.000 créditos",
    creditsPurchased: 1000,
    amountSubtotalCop: 75_630_252,
    amountIvaCop: 14_369_748,
    amountTotalCop: 90_000_000,
    method: "credit_note",
    status: "refunded",
    bankReference: "NC-2026-0007",
    createdAt: ago(14 * DAY),
    paidAt: ago(14 * DAY),
    reconciledByName: "Camila Soto",
    timeline: tl(
      { id: "tl-5-1", timestamp: ago(14 * DAY), type: "created", title: "Factura creada" },
      { id: "tl-5-2", timestamp: ago(14 * DAY), type: "paid", title: "Pago confirmado" },
      {
        id: "tl-5-3",
        timestamp: ago(2 * DAY),
        type: "credit_note_issued",
        title: "Nota crédito emitida",
        description: "Reembolso aprobado por el equipo financiero.",
        actor: "Camila Soto",
      },
      {
        id: "tl-5-4",
        timestamp: ago(2 * DAY),
        type: "refunded",
        title: "Reembolso aplicado",
      },
    ),
  },
  {
    id: "pay-006",
    invoiceNumber: "FAC-2026-0076",
    companyId: "co-0003",
    companyName: "Bavaria S.A.",
    companyTaxId: "NIT 860.005.224-6",
    companyAddress: "Cl. 99 #9-03, Bogotá",
    packageName: "Plan Enterprise · 6.000 créditos",
    creditsPurchased: 6000,
    amountSubtotalCop: 336_134_454,
    amountIvaCop: 63_865_546,
    amountTotalCop: 400_000_000,
    method: "transfer",
    status: "processing",
    bankReference: "TRF-DAVIVIENDA-9001",
    createdAt: ago(18 * HOUR),
    paidAt: null,
    timeline: tl(
      { id: "tl-6-1", timestamp: ago(18 * HOUR), type: "created", title: "Factura creada" },
      {
        id: "tl-6-2",
        timestamp: ago(12 * HOUR),
        type: "processing",
        title: "Transferencia recibida",
        description: "Pendiente de validación contable.",
      },
    ),
  },
  {
    id: "pay-007",
    invoiceNumber: "FAC-2026-0070",
    companyId: "co-0008",
    companyName: "Tiendas Ara",
    companyTaxId: "NIT 900.546.961-1",
    companyAddress: "Cra. 50AA #34-1, Itagüí",
    packageName: "Bolsa A · 1.000 créditos",
    creditsPurchased: 1000,
    amountSubtotalCop: 75_630_252,
    amountIvaCop: 14_369_748,
    amountTotalCop: 90_000_000,
    method: "pse",
    status: "disputed",
    bankReference: "PSE-202604-070-22319",
    errorReason: "bank_rejected",
    createdAt: ago(28 * DAY),
    paidAt: ago(28 * DAY),
    timeline: tl(
      { id: "tl-7-1", timestamp: ago(28 * DAY), type: "created", title: "Factura creada" },
      { id: "tl-7-2", timestamp: ago(28 * DAY), type: "paid", title: "Pago confirmado" },
      {
        id: "tl-7-3",
        timestamp: ago(20 * DAY),
        type: "failed",
        title: "Contra-cargo recibido",
        description: "Cliente disputa la transacción.",
      },
    ),
  },
  {
    id: "pay-008",
    invoiceNumber: "FAC-2026-0058",
    companyId: "co-0001",
    companyName: "Rappi Colombia",
    companyTaxId: "NIT 901.054.391-7",
    companyAddress: "Cl. 93 #19-58, Bogotá",
    packageName: "Bolsa A · 1.000 créditos",
    creditsPurchased: 1000,
    amountSubtotalCop: 75_630_252,
    amountIvaCop: 14_369_748,
    amountTotalCop: 90_000_000,
    method: "pse",
    status: "pending",
    bankReference: "PSE-202604-058-77110",
    createdAt: ago(2 * DAY),
    paidAt: null,
    timeline: tl({
      id: "tl-8-1",
      timestamp: ago(2 * DAY),
      type: "created",
      title: "Factura creada",
    }),
  },
];

export function formatCop(amount: number): string {
  try {
    return new Intl.NumberFormat("es-CO", {
      style: "currency",
      currency: "COP",
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `$${amount.toLocaleString("es-CO")} COP`;
  }
}
