export const billingStrings = {
  page: {
    title: "Pagos y facturación",
    subtitle:
      "Conciliación de pagos, facturas, notas crédito y métricas financieras de toda la plataforma.",
    exportCta: "Exportar movimientos",
    exportToast: "Demo: la exportación se conectará al backend.",
  },
  stats: {
    revenue30d: { label: "Ingresos · 30d", caption: "Pagos conciliados el último mes." },
    pending: { label: "Pendientes", caption: "Facturas a la espera de conciliación." },
    failed: { label: "Pagos fallidos", caption: "Requieren intervención manual." },
    creditNotes: { label: "Notas crédito · 30d", caption: "Reembolsos formales emitidos." },
  },
  filters: {
    searchPlaceholder: "Factura, empresa o referencia bancaria…",
    status: "Estado",
    method: "Método",
    range: "Fecha",
    allStatuses: "Todos los estados",
    allMethods: "Todos los métodos",
    clear: "Limpiar",
    counter: (shown: number, total: number) => `${shown} de ${total} pagos`,
    ranges: {
      "7d": "Últimos 7 días",
      "30d": "Últimos 30 días",
      "90d": "Últimos 90 días",
      all: "Todo el histórico",
    },
  },
  status: {
    paid: "Pagada",
    pending: "Pendiente",
    processing: "En proceso",
    failed: "Fallida",
    refunded: "Reembolsada",
    disputed: "En disputa",
  },
  method: {
    pse: "PSE",
    transfer: "Transferencia",
    card: "Tarjeta",
    credit_note: "Nota crédito",
  },
  table: {
    headers: {
      invoice: "Factura",
      company: "Empresa",
      package: "Paquete",
      amount: "Monto",
      method: "Método",
      status: "Estado",
      date: "Fecha",
      actions: "Acciones",
    },
    empty: "No hay pagos que coincidan con los filtros.",
    viewDetail: "Ver detalle",
    viewInvoice: "Ver factura",
  },
  detail: {
    title: "Detalle del pago",
    description: "Trazabilidad financiera, conciliación contable y evidencia documental.",
    sections: {
      summary: "Resumen",
      timeline: "Línea de tiempo",
      error: "Estado de error",
      actions: "Acciones",
    },
    fields: {
      invoice: "Factura",
      company: "Empresa",
      taxId: "NIT",
      package: "Paquete",
      credits: "Créditos",
      method: "Método",
      bankRef: "Referencia bancaria",
      subtotal: "Subtotal",
      iva: "IVA (19%)",
      total: "Total",
      createdAt: "Creada",
      paidAt: "Pagada",
      reconciledBy: "Conciliada por",
    },
    actions: {
      viewInvoice: "Ver factura",
      retry: "Reintentar conciliación",
      markFailed: "Marcar como fallida",
      issueCreditNote: "Emitir nota crédito",
      reconcile: "Marcar conciliada",
      retryToast: "Demo: reintentando conciliación…",
      markedFailedToast: "Demo: pago marcado como fallido.",
      reconciledToast: "Demo: pago marcado como conciliado.",
      creditNoteToast: "Demo: nota crédito generada.",
    },
    error: {
      insufficient_funds: "Fondos insuficientes en la cuenta del cliente.",
      bank_rejected: "Rechazado por el banco emisor.",
      timeout_pse: "Timeout durante la confirmación PSE.",
      gateway_error: "Error en la pasarela de pagos.",
    },
  },
  timelineLabels: {
    created: "Factura creada",
    processing: "Pago en proceso",
    paid: "Pago confirmado",
    failed: "Pago fallido",
    refunded: "Reembolso emitido",
    reconciled: "Conciliación contable",
    credit_note_issued: "Nota crédito emitida",
  },
  invoice: {
    title: "Factura electrónica",
    description: "Documento demostrativo. No tiene validez fiscal.",
    issuer: {
      name: "Licénciame S.A.S.",
      taxId: "NIT 901.456.789-2",
      address: "Cra. 11 #93-46, Bogotá D.C., Colombia",
      email: "facturacion@licenciame.com",
    },
    fields: {
      invoiceNumber: "N.º de factura",
      issueDate: "Fecha de emisión",
      dueDate: "Fecha de pago",
      method: "Método de pago",
      bankRef: "Referencia",
      bilingTo: "Facturar a",
      taxId: "NIT",
      address: "Dirección",
    },
    table: {
      concept: "Concepto",
      qty: "Cantidad",
      unitPrice: "Valor unitario",
      total: "Total",
    },
    totals: {
      subtotal: "Subtotal",
      iva: "IVA (19%)",
      total: "Total a pagar",
    },
    download: "Descargar PDF",
    downloadToast: "Demo: la descarga PDF se conectará al backend.",
    stamp: "DOCUMENTO DEMO · NO VÁLIDO FISCALMENTE",
    close: "Cerrar",
  },
} as const;
