import type { AdminLicense, LicenseEvidenceEvent } from "./types";

const HOUR = 3_600_000;
const DAY = 86_400_000;
const now = Date.now();
const ago = (ms: number) => new Date(now - ms).toISOString();
const future = (ms: number) => new Date(now + ms).toISOString();

export const adminLicensesCompanies = [
  "Rappi Colombia",
  "Banco Andino",
  "Postobón S.A.",
  "Tiendas D1",
  "Bavaria S.A.",
  "Grupo Éxito",
  "Tiendas Ara",
  "Marca Demo S.A.S.",
];

function evidence(...events: LicenseEvidenceEvent[]): LicenseEvidenceEvent[] {
  return events;
}

export const adminLicensesMocks: AdminLicense[] = [
  // Caso destacado: track oculto con licencia activa
  {
    id: "lic-001",
    tokenId: "LIC-K7H3-2026",
    trackId: "trk-00091",
    trackTitle: "Verano en la ciudad",
    trackArtist: "Lúa Moreno",
    trackIsrc: "CO-X12-25-00091",
    trackHidden: true,
    companyId: "co-0001",
    companyName: "Rappi Colombia",
    usageType: "monthly-extended",
    creditsConsumed: 13,
    status: "active",
    issuedAt: ago(10 * DAY),
    expiresAt: future(20 * DAY),
    consumedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Mariana López",
    issuedByUserEmail: "mariana.lopez@rappi.com",
    evidence: evidence(
      {
        id: "ev-1-1",
        timestamp: ago(10 * DAY),
        type: "issued",
        title: "Licencia emitida",
        description: "Generada desde el catálogo. Crédito descontado del balance.",
        actor: "Mariana López",
      },
      {
        id: "ev-1-2",
        timestamp: ago(8 * DAY),
        type: "first_use_detected",
        title: "Primer uso detectado",
        description: "Detección automática en Instagram Reels.",
        platform: "instagram",
        url: "https://instagram.com/rappi/reel/demo-001",
      },
      {
        id: "ev-1-3",
        timestamp: ago(5 * DAY),
        type: "publication",
        title: "Publicación adicional",
        description: "Re-publicación en TikTok corporativo.",
        platform: "tiktok",
        url: "https://tiktok.com/@rappi/video/demo-002",
      },
      {
        id: "ev-1-4",
        timestamp: ago(1.5 * DAY),
        type: "track_hidden",
        title: "Track ocultado del catálogo",
        description:
          "Soft delete aplicado por Camila Soto. La evidencia se conserva mientras existan licencias activas.",
        actor: "Camila Soto",
      },
    ),
  },
  {
    id: "lic-002",
    tokenId: "LIC-A2B5-2026",
    trackId: "trk-00318",
    trackTitle: "Lluvia en Bogotá",
    trackArtist: "Aire Quieto",
    trackIsrc: "CO-X12-25-00318",
    trackHidden: false,
    companyId: "co-0014",
    companyName: "Postobón S.A.",
    usageType: "paid-post",
    creditsConsumed: 8,
    status: "active",
    issuedAt: ago(2 * DAY),
    expiresAt: null,
    consumedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Andrés Quintero",
    issuedByUserEmail: "aquintero@postobon.com",
    evidence: evidence({
      id: "ev-2-1",
      timestamp: ago(2 * DAY),
      type: "issued",
      title: "Licencia emitida",
      description: "Generada desde el flujo de licenciamiento.",
      actor: "Andrés Quintero",
    }),
  },
  {
    id: "lic-003",
    tokenId: "LIC-X9P2-2026",
    trackId: "trk-00472",
    trackTitle: "Atardecer en Cartagena",
    trackArtist: "Mariana Vélez",
    trackIsrc: "CO-X12-25-00472",
    trackHidden: false,
    companyId: "co-0008",
    companyName: "Tiendas Ara",
    usageType: "stories-pack",
    creditsConsumed: 1,
    status: "consumed",
    issuedAt: ago(15 * DAY),
    expiresAt: null,
    consumedAt: ago(13 * DAY),
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Lucía Torres",
    issuedByUserEmail: "lucia.torres@ara.co",
    evidence: evidence(
      {
        id: "ev-3-1",
        timestamp: ago(15 * DAY),
        type: "issued",
        title: "Licencia emitida",
        description: "Pack de stories Instagram.",
        actor: "Lucía Torres",
      },
      {
        id: "ev-3-2",
        timestamp: ago(13 * DAY),
        type: "publication",
        title: "Stories publicados",
        description: "5 stories detectados en cuenta corporativa.",
        platform: "instagram",
        url: "https://instagram.com/ara_co/stories/demo",
      },
    ),
  },
  {
    id: "lic-004",
    tokenId: "LIC-M2N9-2026",
    trackId: "trk-00128",
    trackTitle: "Latido eléctrico",
    trackArtist: "Nodo Sur",
    trackIsrc: "CO-X12-25-00128",
    trackHidden: false,
    companyId: "co-0003",
    companyName: "Bavaria S.A.",
    usageType: "long-video",
    creditsConsumed: 5,
    status: "disputed",
    issuedAt: ago(45 * DAY),
    expiresAt: null,
    consumedAt: ago(40 * DAY),
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Carolina Pérez",
    issuedByUserEmail: "cperez@bavaria.com",
    evidence: evidence(
      {
        id: "ev-4-1",
        timestamp: ago(45 * DAY),
        type: "issued",
        title: "Licencia emitida",
        description: "Para video institucional.",
      },
      {
        id: "ev-4-2",
        timestamp: ago(40 * DAY),
        type: "publication",
        title: "Video publicado",
        description: "YouTube oficial Bavaria.",
        platform: "youtube",
        url: "https://youtube.com/watch?v=demo-bavaria",
      },
      {
        id: "ev-4-3",
        timestamp: ago(9 * DAY),
        type: "disputed",
        title: "Disputa abierta",
        description:
          "Empresa reporta que el uso fue distinto al licenciado. Revisión legal en curso.",
        actor: "Camila Soto",
      },
    ),
  },
  {
    id: "lic-005",
    tokenId: "LIC-Q4R7-2025",
    trackId: "trk-00211",
    trackTitle: "Madrugada limpia",
    trackArtist: "Aire Quieto",
    trackIsrc: "CO-X12-25-00211",
    trackHidden: false,
    companyId: "co-0007",
    companyName: "Grupo Éxito",
    usageType: "single-use",
    creditsConsumed: 2,
    status: "expired",
    issuedAt: ago(95 * DAY),
    expiresAt: ago(35 * DAY),
    consumedAt: ago(90 * DAY),
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Felipe Ramírez",
    issuedByUserEmail: "framirez@exito.com",
    evidence: evidence({
      id: "ev-5-1",
      timestamp: ago(95 * DAY),
      type: "issued",
      title: "Licencia emitida",
      description: "Campaña de retail navideña.",
    }),
  },
  {
    id: "lic-006",
    tokenId: "LIC-T8L2-2026",
    trackId: "trk-00455",
    trackTitle: "Costa norte",
    trackArtist: "Selva Roja",
    trackIsrc: "CO-X12-25-00455",
    trackHidden: false,
    companyId: "co-0002",
    companyName: "Banco Andino",
    usageType: "collaborative-post",
    creditsConsumed: 9,
    status: "cancelled",
    issuedAt: ago(28 * DAY),
    expiresAt: null,
    consumedAt: null,
    cancelledAt: ago(27 * DAY),
    cancellationReason: "Tipo de uso incorrecto seleccionado.",
    issuedByUserName: "Andrés Quintero",
    issuedByUserEmail: "aquintero@bancoandino.co",
    evidence: evidence(
      {
        id: "ev-6-1",
        timestamp: ago(28 * DAY),
        type: "issued",
        title: "Licencia emitida",
        description: "Post colaborativo con creador.",
      },
      {
        id: "ev-6-2",
        timestamp: ago(27 * DAY),
        type: "cancelled",
        title: "Licencia cancelada",
        description: "Cancelada dentro de la ventana de 48h. Crédito reembolsado.",
        actor: "Andrés Quintero",
      },
    ),
  },
  {
    id: "lic-007",
    tokenId: "LIC-Z1Y8-2026",
    trackId: "trk-00399",
    trackTitle: "Cumbia sintética",
    trackArtist: "Los Picos",
    trackIsrc: "CO-X12-25-00399",
    trackHidden: false,
    companyId: "co-0004",
    companyName: "Tiendas D1",
    usageType: "stories-pack",
    creditsConsumed: 1,
    status: "active",
    issuedAt: ago(0.5 * DAY),
    expiresAt: null,
    consumedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Sandra Olivera",
    issuedByUserEmail: "solivera@d1.com.co",
    evidence: evidence({
      id: "ev-7-1",
      timestamp: ago(0.5 * DAY),
      type: "issued",
      title: "Licencia emitida",
      description: "Recién generada.",
    }),
  },
  {
    id: "lic-008",
    tokenId: "LIC-W5K3-2026",
    trackId: "trk-00501",
    trackTitle: "Ruta 70",
    trackArtist: "Brava",
    trackIsrc: "CO-X12-25-00501",
    trackHidden: false,
    companyId: "co-0001",
    companyName: "Rappi Colombia",
    usageType: "monthly-extended",
    creditsConsumed: 13,
    status: "active",
    issuedAt: ago(20 * HOUR),
    expiresAt: future(30 * DAY - 20 * HOUR),
    consumedAt: null,
    cancelledAt: null,
    cancellationReason: null,
    issuedByUserName: "Mariana López",
    issuedByUserEmail: "mariana.lopez@rappi.com",
    evidence: evidence({
      id: "ev-8-1",
      timestamp: ago(20 * HOUR),
      type: "issued",
      title: "Licencia emitida",
      description: "Campaña mensual.",
    }),
  },
];
