export const licensesStrings = {
  page: {
    title: "Licencias",
    subtitle:
      "Búsqueda y revisión de licencias emitidas en toda la plataforma. Vigencias, evidencias y casos sensibles.",
    exportCta: "Exportar listado",
    exportToast: "Demo: la exportación se conectará al backend.",
  },
  stats: {
    active: { label: "Activas", caption: "Licencias vigentes hoy." },
    issued30d: { label: "Emitidas · 30d", caption: "Licencias generadas el último mes." },
    expired: { label: "Vencidas", caption: "Pasaron su período de vigencia." },
    disputed: { label: "En disputa", caption: "Casos abiertos por equipo legal." },
  },
  filters: {
    searchPlaceholder: "Token, ISRC, track o empresa…",
    status: "Estado",
    usageType: "Tipo de uso",
    company: "Empresa",
    range: "Emisión",
    onlyHiddenTracks: "Solo tracks ocultos con licencia activa",
    allStatuses: "Todos los estados",
    allUsage: "Todos los usos",
    allCompanies: "Todas las empresas",
    clear: "Limpiar",
    counter: (shown: number, total: number) => `${shown} de ${total} licencias`,
    ranges: {
      "7d": "Últimos 7 días",
      "30d": "Últimos 30 días",
      "90d": "Últimos 90 días",
      all: "Todo el histórico",
    },
  },
  status: {
    active: "Activa",
    consumed: "Consumida",
    expired: "Vencida",
    cancelled: "Cancelada",
    disputed: "En disputa",
  },
  usageType: {
    "single-use": "Uso único",
    "stories-pack": "Pack stories",
    "monthly-extended": "Extendido mensual",
    "long-video": "Video largo",
    "paid-post": "Post pagado",
    "collaborative-post": "Post colaborativo",
  },
  table: {
    headers: {
      token: "Token",
      track: "Track",
      company: "Empresa",
      usage: "Uso",
      credits: "Créditos",
      status: "Estado",
      issued: "Emitida",
      expires: "Vence/Consume",
      actions: "Acciones",
    },
    empty: "No hay licencias que coincidan con los filtros.",
    viewDetail: "Ver detalle",
  },
  detail: {
    title: "Detalle de licencia",
    description: "Snapshot del track, empresa licenciataria y evidencia histórica de uso.",
    tabs: {
      summary: "Resumen",
      evidence: "Evidencia",
    },
    fields: {
      token: "Token de licencia",
      isrc: "ISRC",
      company: "Empresa",
      issuedBy: "Emitida por",
      usage: "Tipo de uso",
      credits: "Créditos consumidos",
      issuedAt: "Fecha de emisión",
      expiresAt: "Vence",
      consumedAt: "Consumida",
      cancelledAt: "Cancelada",
      cancelReason: "Motivo de cancelación",
      noExpiry: "Sin vencimiento",
    },
    evidence: {
      empty: "Aún no hay eventos de evidencia registrados.",
      types: {
        issued: "Licencia emitida",
        first_use_detected: "Primer uso detectado",
        publication: "Publicación detectada",
        legal_review: "Revisión legal",
        renewed: "Licencia renovada",
        cancelled: "Licencia cancelada",
        disputed: "Disputa abierta",
        track_hidden: "Track ocultado del catálogo",
      },
      openLink: "Ver publicación",
    },
    hiddenBanner: {
      title: "Track oculto del catálogo público",
      body: "Esta licencia sigue vigente. La evidencia se preserva por obligación legal mientras existan licencias activas.",
      cta: "Ir al track en catálogo",
    },
  },
} as const;
