/**
 * MOCK ONLY — F-09 Catalog admin fixtures.
 * Replace with real API responses when backend lands.
 */
import type { AdminTrack, CatalogStatsMock } from "./types";

export const adminCatalogStats: CatalogStatsMock = {
  total: 15000,
  active: 14620,
  hidden: 128,
  legalReview: 37,
  withActiveLicenses: 3920,
  lastUpdateLabel: "Hace 18 días",
};

export const adminCatalogGenres = [
  "Electro Pop",
  "Ambient / Corporate",
  "Urban Latin",
  "Acoustic",
  "Dance",
  "Indie Pop",
  "Cinematic",
] as const;

export const adminCatalogTracks: AdminTrack[] = [
  {
    id: "trk_001",
    isrc: "COLM12300001",
    title: "Midnight Pulse",
    artist: "Lía Navarro",
    genre: "Electro Pop",
    mood: "Energético",
    durationSeconds: 198,
    creditsRequired: 12,
    status: "active",
    activeLicenses: 248,
    uploadedAt: "2024-09-12",
    updatedAt: "2026-04-10",
    recommendedUse: "Campañas digitales, brand films de producto.",
    legalNotes: "Master y publishing administrados por Licénciame Music S.A.",
    tags: ["digital", "brand-film", "pop"],
    hasCompleteMetadata: true,
    licensees: [
      { companyId: "cmp_rappi", companyName: "Rappi Colombia", licenses: 42 },
      { companyId: "cmp_banco", companyName: "Banco Andino", licenses: 18 },
      { companyId: "cmp_uninorte", companyName: "Universidad Norte", licenses: 9 },
    ],
  },
  {
    id: "trk_002",
    isrc: "COLM12300002",
    title: "Corporate Motion",
    artist: "Andrés Bohórquez",
    genre: "Ambient / Corporate",
    mood: "Inspiracional",
    durationSeconds: 215,
    creditsRequired: 10,
    status: "active",
    activeLicenses: 181,
    uploadedAt: "2024-07-04",
    updatedAt: "2026-03-29",
    recommendedUse: "Videos corporativos, presentaciones internas.",
    legalNotes: "Sin restricciones territoriales.",
    tags: ["corporate", "ambient"],
    hasCompleteMetadata: true,
    licensees: [
      { companyId: "cmp_postobon", companyName: "Postobón S.A.", licenses: 64 },
      { companyId: "cmp_avianca", companyName: "Avianca", licenses: 31 },
    ],
  },
  {
    id: "trk_003",
    isrc: "COLM12300003",
    title: "Golden Reels",
    artist: "Sara Mendoza",
    genre: "Urban Latin",
    mood: "Festivo",
    durationSeconds: 172,
    creditsRequired: 14,
    status: "active",
    activeLicenses: 92,
    uploadedAt: "2025-01-18",
    updatedAt: "2026-04-02",
    recommendedUse: "Reels, stories, contenido orgánico social.",
    legalNotes: "Permitido en TikTok, Instagram y YouTube Shorts.",
    tags: ["reels", "urban", "social"],
    hasCompleteMetadata: true,
    licensees: [
      { companyId: "cmp_dlk", companyName: "D.LK Studio", licenses: 27 },
    ],
  },
  {
    id: "trk_004",
    isrc: "COLM12300004",
    title: "Soft Horizon",
    artist: "Esteban Caro",
    genre: "Acoustic",
    mood: "Calmo",
    durationSeconds: 240,
    creditsRequired: 8,
    status: "hidden",
    activeLicenses: 17,
    uploadedAt: "2023-11-20",
    updatedAt: "2026-03-15",
    recommendedUse: "Pieza de cierre, locuciones, branded podcast.",
    legalNotes: "Track oculto del catálogo activo. Licencias previas siguen vigentes.",
    tags: ["acoustic", "podcast"],
    hasCompleteMetadata: true,
    licensees: [
      { companyId: "cmp_ondas", companyName: "Ondas FM", licenses: 12 },
    ],
  },
  {
    id: "trk_005",
    isrc: "COLM12300005",
    title: "Event Drive",
    artist: "Camila Riveros",
    genre: "Dance",
    mood: "Alta energía",
    durationSeconds: 188,
    creditsRequired: 16,
    status: "legal_review",
    activeLicenses: 0,
    uploadedAt: "2026-02-05",
    updatedAt: "2026-04-12",
    recommendedUse: "Activaciones BTL, eventos masivos.",
    legalNotes: "En revisión: pendiente confirmación de splits con co-autor.",
    tags: ["events", "dance"],
    hasCompleteMetadata: false,
    licensees: [],
  },
  {
    id: "trk_006",
    isrc: "COLM12300006",
    title: "Creator Spark",
    artist: "Indie Coast",
    genre: "Indie Pop",
    mood: "Optimista",
    durationSeconds: 205,
    creditsRequired: 11,
    status: "active",
    activeLicenses: 54,
    uploadedAt: "2025-05-09",
    updatedAt: "2026-04-08",
    recommendedUse: "Lanzamientos de producto, contenido de marca emergente.",
    legalNotes: "Disponible global salvo SYNC en TV abierta.",
    tags: ["indie", "creator", "launch"],
    hasCompleteMetadata: true,
    licensees: [
      { companyId: "cmp_belcorp", companyName: "Belcorp", licenses: 22 },
    ],
  },
];
