/**
 * F-09 Catalog admin — UI strings (Spanish only, code in English).
 */
export const catalogStrings = {
  page: {
    title: "Gestión de catálogo",
    subtitle:
      "Administra tracks, metadata, disponibilidad y estados legales del catálogo musical.",
    addTrack: "Agregar track",
    importCsv: "Importar CSV",
    exportCsv: "Exportar catálogo",
  },
  stats: {
    total: "Total tracks",
    active: "Activos",
    hidden: "Ocultos",
    legalReview: "En revisión legal",
    withActiveLicenses: "Con licencias activas",
    lastUpdate: "Última actualización",
  },
  filters: {
    searchPlaceholder: "Buscar por track, artista o ID…",
    status: "Estado",
    genre: "Género",
    allStatuses: "Todos los estados",
    allGenres: "Todos los géneros",
    onlyWithLicenses: "Con licencias activas",
    onlyMissingMetadata: "Sin metadata completa",
    updatedWithin: "Actualización",
    updated: {
      "7d": "Últimos 7 días",
      "30d": "Últimos 30 días",
      "90d": "Últimos 90 días",
      all: "Cualquier fecha",
    },
    counter: (shown: number, total: number) =>
      `Mostrando ${shown.toLocaleString("es-CO")} de ${total.toLocaleString("es-CO")} tracks`,
    clear: "Limpiar filtros",
  },
  status: {
    active: "Activo",
    hidden: "Oculto",
    legal_review: "En revisión legal",
    unavailable: "No disponible",
    pending_metadata: "Pendiente metadata",
  },
  table: {
    track: "Track",
    artist: "Artista",
    genre: "Género",
    mood: "Mood / uso",
    duration: "Duración",
    credits: "Créditos",
    status: "Estado",
    activeLicenses: "Licencias activas",
    updatedAt: "Última actualización",
    actions: "Acciones",
    emptyTitle: "No encontramos tracks con esos filtros",
    emptyDescription: "Ajusta búsqueda, estado o género para ver más resultados.",
    metadataIncomplete: "Metadata incompleta",
  },
  rowActions: {
    viewDetail: "Ver detalle",
    editMetadata: "Editar metadata",
    hide: "Ocultar del catálogo",
    restore: "Restaurar",
    viewLicenses: "Ver licencias asociadas",
  },
  detail: {
    title: "Detalle del track",
    description: "Información operativa, legal y comercial del track seleccionado.",
    fields: {
      title: "Nombre",
      artist: "Artista",
      isrc: "ISRC / ID interno",
      genre: "Género",
      mood: "Mood",
      duration: "Duración",
      credits: "Créditos requeridos",
      status: "Estado",
      activeLicenses: "Licencias activas",
      uploadedAt: "Fecha de carga",
      updatedAt: "Última actualización",
      recommendedUse: "Uso recomendado",
      legalNotes: "Notas legales",
    },
    licensees: {
      title: "Licencias activas asociadas",
      empty: "Aún no hay empresas con licencias activas para este track.",
      licensesUnit: (n: number) => `${n.toLocaleString("es-CO")} licencias`,
    },
    actions: {
      edit: "Editar metadata",
      hide: "Ocultar del catálogo",
      restore: "Restaurar al catálogo",
    },
  },
  form: {
    addTitle: "Agregar track",
    editTitle: "Editar metadata",
    description:
      "Cambios en modo demo: no se persisten en backend ni se notifican a empresas.",
    fields: {
      title: "Nombre del track",
      artist: "Artista",
      genre: "Género",
      mood: "Mood",
      duration: "Duración (segundos)",
      credits: "Créditos requeridos",
      status: "Estado",
      tags: "Tags de uso (separados por coma)",
      legalNotes: "Notas legales",
      audioFile: "Archivo de audio",
      coverImage: "Cover image",
      audioHint: "Sólo UI demo · No se realiza upload real.",
    },
    cancel: "Cancelar",
    save: "Guardar cambios",
    create: "Crear track",
    toastSaved: "Cambios guardados en modo demo.",
    toastCreated: "Track creado en modo demo.",
  },
  hide: {
    safe: {
      title: "Ocultar track del catálogo",
      body: "Este track dejará de estar disponible para nuevas licencias. Las licencias previas, si existen, conservarán su evidencia.",
      confirm: "Ocultar track",
    },
    critical: {
      title: "No se puede eliminar definitivamente este track",
      body: "Este track tiene licencias activas. Para preservar evidencia legal, sólo puedes ocultarlo del catálogo. Las licencias existentes conservarán su información histórica.",
      confirm: "Ocultar con soft delete",
      preservesEvidence: "Preserva evidencia legal",
    },
    cancel: "Cancelar",
    toastHidden: "Track oculto del catálogo en modo demo.",
    toastRestored: "Track restaurado al catálogo en modo demo.",
  },
  importExport: {
    open: "Importar CSV",
    title: "Gestión masiva de catálogo",
    description:
      "Carga masiva de tracks vía CSV con validación previa. Demo · sin upload ni procesamiento real.",
    steps: {
      upload: "Subir archivo",
      preview: "Validación",
      result: "Resultado",
    },
    upload: {
      dropzone: "Arrastra tu archivo o haz click para seleccionarlo",
      hint: "Sube un archivo .CSV con tracks y metadata.",
      cta: "Seleccionar archivo",
      mock: "demo_catalogo_abr2026.csv",
      next: "Validar archivo",
      template: "Descargar plantilla CSV (demo)",
    },
    preview: {
      summary: "Resumen de validación",
      newTracks: "Nuevos tracks detectados",
      updates: "Actualizaciones",
      errors: "Errores de metadata",
      conflicts: "Conflictos legales",
      issuesTitle: "Incidencias detectadas",
      issues: {
        missingColumns: "Faltan columnas obligatorias en 4 filas.",
        duplicates: "Hay 7 tracks duplicados por ISRC.",
        legalConflicts:
          "Hay 3 tracks con licencias activas que requieren revisión antes de actualizar.",
      },
      back: "Volver",
      confirm: "Aplicar cambios (demo)",
    },
    result: {
      successTitle: "Importación simulada completada",
      successBody:
        "En producción, los cambios se aplicarían y se notificaría al equipo de operación.",
      close: "Cerrar",
    },
    export: {
      toast: "Exportación simulada generada.",
    },
  },
  operationalNote: {
    badge: "Pendiente por definición operativa",
    title: "Cómo subimos y actualizamos los 15K tracks",
    body: "No se define aún cómo se sube o actualiza el catálogo completo de 15.000 tracks. Esta vista propone import/export CSV y soft delete como solución operativa inicial, mientras se acuerda el flujo definitivo con producto.",
  },
} as const;
