export const catalogStrings = {
  page: {
    title: "Catálogo musical",
    subtitle: "Explora más de 15.000 canciones listas para licenciar",
  },
  search: {
    placeholder: "Busca por título, artista o género…",
    ariaLabel: "Buscar canciones",
    clear: "Limpiar búsqueda",
    noResults: {
      title: 'No encontramos canciones para "{query}"',
      description: "Prueba con otros términos o explora estos géneros populares:",
    },
  },
  header: {
    results: "{count, plural, one {# canción encontrada} other {# canciones encontradas}}",
    filtersButton: "Filtros",
  },
  viewMode: {
    grid: "Vista de cuadrícula",
    list: "Vista de lista",
  },
  themed: {
    title: "Descubre por tipo de contenido",
    reels: { title: "Reels e historias", description: "Tracks cortos y pegadizos para IG y TikTok." },
    events: { title: "Eventos y shows", description: "Energía alta para activaciones en vivo." },
    corporate: { title: "Contenido corporativo", description: "Música institucional y elegante." },
    podcasts: { title: "Pódcasts y vlogs", description: "Bases sutiles que no compiten con la voz." },
  },
  filters: {
    title: "Filtros",
    clear: "Limpiar filtros",
    apply: "Aplicar",
    applyAll: "Aplicar filtros",
    activeCount: "{count} activos",
    close: "Cerrar filtros",
    resultsCount: "{count, plural, one {# canción} other {# canciones}}",
    sections: {
      genre: "Género",
      mood: "Mood",
      duration: "Duración",
      platform: "Disponible en",
      favorites: "Favoritos",
    },
    duration: {
      label: "Rango de duración",
      any: "Cualquiera",
      minToMax: "{min} - {max}",
    },
    platform: {
      instagram: "Instagram",
      tiktok: "TikTok",
      facebook: "Facebook",
    },
    favorites: {
      onlyMine: "Mostrar solo mis favoritos",
    },
    genres: {
      viewMore: "Ver más",
      viewLess: "Ver menos",
    },
    activeChips: {
      clearAll: "Limpiar todo",
      removeOne: "Quitar filtro {label}",
      genre: "Género: {value}",
      mood: "Mood: {value}",
      platform: "Plataforma: {value}",
      duration: "Duración: {min} - {max}",
      favorites: "Solo favoritos",
      search: 'Búsqueda: "{value}"',
    },
    sort: {
      label: "Ordenar por",
      ariaLabel: "Cambiar orden de resultados",
      options: {
        "popularity-desc": "Más populares",
        "recent-desc": "Más recientes",
        "title-asc": "Título (A-Z)",
        "title-desc": "Título (Z-A)",
        "duration-asc": "Duración (menor a mayor)",
        "duration-desc": "Duración (mayor a menor)",
        "artist-asc": "Artista (A-Z)",
      },
    },
    pageSize: {
      label: "Mostrar",
      ariaLabel: "Cantidad de resultados por página",
      option: "{size} por página",
    },
  },
  trackCard: {
    licenseCta: "Licenciar",
    playPreview: "Reproducir preview",
    pausePreview: "Pausar preview",
    addToFavorites: "Agregar a favoritos",
    removeFromFavorites: "Quitar de favoritos",
    viewDetails: "Ver detalles de {title}",
    licensableOn: "Licenciable en {platform}",
    notLicensableOn: "No licenciable en {platform}",
    coverAlt: "Carátula de {title} de {artist}",
    coverPlaceholder: "Sin carátula",
  },
  pagination: {
    label: "Paginación del catálogo",
    prev: "Anterior",
    next: "Siguiente",
    pageXofY: "Página {page} de {total}",
    goToPage: "Ir a la página {page}",
    morePages: "Más páginas",
    compact: "Página {page} de {total}",
  },
  states: {
    loading: "Cargando catálogo…",
    error: {
      title: "No pudimos cargar el catálogo",
      description: "Intenta de nuevo en unos segundos.",
      cta: "Reintentar",
    },
    empty: {
      title: "El catálogo está vacío por ahora",
      description: "Vuelve pronto, estamos agregando música constantemente.",
    },
    filteredEmpty: {
      title: "Ningún track coincide con tus filtros",
      description: "Prueba quitando alguno de los filtros activos para ampliar los resultados.",
      cta: "Limpiar filtros",
    },
    trackRemoved: {
      title: "Esta canción ya no está disponible",
      description: "Fue removida del catálogo. Explora alternativas similares.",
      cta: "Volver al catálogo",
    },
  },
  trackDetail: {
    backToCatalog: "Volver al catálogo",
    licenseNow: "Licenciar canción",
    playPreview: "Reproducir preview",
    pausePreview: "Pausar preview",
    favoriteAdd: "Agregar a favoritos",
    favoriteRemove: "Quitar de favoritos",
    metaTitle: "Información",
    metadata: {
      artist: "Artista",
      album: "Álbum",
      genre: "Género",
      duration: "Duración",
      releaseYear: "Año",
      bpm: "BPM",
      language: "Idioma",
      isrc: "ISRC",
      isrcTooltip: "International Standard Recording Code",
      moods: "Mood",
      tags: "Tags",
    },
    waveform: {
      previewLimited: "Preview limitado a 30 segundos",
      positionStart: "0:00",
      positionEnd: "0:30",
      ariaLabel: "Línea de tiempo del preview",
    },
    notAvailable: "No disponible",
  },
  licensability: {
    title: "Condiciones de licenciabilidad",
    subtitle: "Revisa qué usos están permitidos antes de licenciar",
    usageTypeHeader: "Tipo de uso",
    allowed: "Permitido",
    notAllowed: "No disponible",
    withConditions: "Con condiciones",
    maxDuration: "Máximo {seconds} segundos",
    legalNote:
      "* Consulta las condiciones específicas al momento de licenciar. Algunas restricciones pueden aplicar según la duración o el tipo de publicación.",
    captionFor: "Matriz de licenciabilidad para {title}",
    cellAriaAllowed: "{platform} {usageType}: Permitido{suffix}",
    cellAriaDenied: "{platform} {usageType}: No disponible",
    withMaxDurationSuffix: ", máximo {seconds} segundos",
    platforms: {
      instagram: "Instagram",
      tiktok: "TikTok",
      facebook: "Facebook",
    },
    usageTypes: {
      "single-use": "Uso único",
      "stories-pack": "Paquete stories",
      "monthly-extended": "Uso extendido mensual",
      "long-video": "Video largo (1-3 min)",
      "paid-post": "Post con pauta paga",
      "collaborative-post": "Post colaborativo",
    },
  },
  similarTracks: {
    title: "Canciones similares",
    subtitle: "Basado en el género {genre}",
  },
  trackDetailStates: {
    notFound: {
      title: "Esta canción no existe",
      description: "El link que intentaste abrir no corresponde a ninguna canción del catálogo.",
      cta: "Volver al catálogo",
    },
    removed: {
      title: "Esta canción ya no está disponible",
      description: "Fue removida del catálogo. Explora alternativas similares.",
      ctaPrimary: "Volver al catálogo",
      ctaSecondary: "Ver más populares",
    },
    error: {
      title: "No pudimos cargar el detalle",
      description: "Revisa tu conexión e inténtalo de nuevo.",
      retry: "Reintentar",
    },
  },
  a11y: {
    skipToResults: "Saltar a resultados",
    searchShortcut: "Pulsa / para buscar",
    resultsLive: "{count} resultados",
    activeFilters: "Filtros activos",
  },
  genres: {
    pop: "Pop",
    rock: "Rock",
    electronic: "Electrónica",
    "hip-hop": "Hip-hop",
    jazz: "Jazz",
    classical: "Clásica",
    latin: "Latino",
    reggaeton: "Reggaetón",
    indie: "Indie",
    rnb: "R&B",
    folk: "Folk",
    ambient: "Ambient",
    cinematic: "Cinematográfica",
    corporate: "Corporativa",
    acoustic: "Acústica",
    world: "World",
  },
} as const;
